#!/bin/bash

#To configure Albany on Hopper: source this file 

#IK, 10/1/13
#prior to configuring you need to load the following modules: 

rm -f CMakeCache.txt
cmake  \
    -D ALBANY_TRILINOS_DIR:FILEPATH="${TRILINSTALLDIR}" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -D ENABLE_DEMO_PDES=OFF -D ENABLE_SG=OFF -D ENABLE_ENSEMBLE=OFF -D ENABLE_MOR=OFF -DENABLE_QCAD=OFF  -DENABLE_ASCR=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D ENABLE_FAST_FELIX:BOOL=ON \
    -D ENABLE_LCM:BOOL=OFF \
    ..

# ToDO: get this working on Titan
#    -D ENABLE_GPTL:BOOL=ON \
#    -D GPTL_INCLUDE_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
#    -D GPTL_LIBRARY_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
