#!/bin/bash
# This is a sample Albany configuration script

# Cleanup old cmake files
rm -rf CMake*

#FIXME: the following needs needs to be changed to point to your Trilinos install! 
TRILINOS_INSTALL_DIR=

#FIXME: the following needs to be changed to point to Albany's source directory
ALBANY_SOURCE_DIR=

ALBANY_INSTALL_DIR="./install"

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH=${TRILINOS_INSTALL_DIR} \
      -D CMAKE_INSTALL_PREFIX:PATH=${ALBANY_INSTALL_DIR} \
      -D CMAKE_CXX_FLAGS:STRING="" \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -D ENABLE_DEMO_PDES:BOOL=OFF \
      -D ENABLE_LANDICE:BOOL=ON \
      -D ENABLE_MESH_DEPENDS_ON_PARAMETERS:BOOL=OFF \
      -D BUILD_SHARED_LIBS:BOOL=ON \
      -D Albany_BUILD_STATIC_EXE:BOOL=OFF \
\
      -D ALBANY_TAN_SLFAD_SIZE=100 \
      -D ALBANY_SLFAD_SIZE=90 \
      -D ENABLE_FAD_TYPE:STRING="SLFad" \
      -D ENABLE_TAN_FAD_TYPE:STRING="SLFad" \
\
      -D ENABLE_MPAS_INTERFACE:BOOL=ON \
      -D ENABLE_ALBANY_EPETRA=OFF \
${ALBANY_SOURCE_DIR}

# Include these flags if you want to enable PyAlbany
#  -D ENABLE_ALBANY_PYTHON=ON \
#  -D PYTHON_EXECUTABLE=/global/common/software/nersc/pm-2022q3/sw/python/3.9-anaconda-2021.11/bin/python \
