#!/bin/sh

TRILINOS_DIR=/projects/AppComp/nightly_gahanse/cee-compute011/test



cmake \
    -DALBANY_TRILINOS_DIR:PATH=${TRILINOS_DIR}/TrilinosInstallC11 \
    -DENABLE_LANDICE:BOOL=ON \
    -DENABLE_UNIT_TESTS:BOOL=ON \
    -DENABLE_64BIT_INT:BOOL=ON \
    -DENABLE_DEMO_PDES:BOOL=ON \
    -DENABLE_STRONG_FPE_CHECK:BOOL=ON \
..

exit 0
