#!/bin/bash

if [ $# -ne 1 ]; then
   echo "Usage: $0 -d (debug)"
   echo "Usage: $0 -r (release)"
   exit 1
elif [ $1 = "-d" ]; then
   export TRILINOS_INSTALL_DIR=/usr/local/trilinos/MPI_DBG
elif [ $1 = "-r" ]; then
   export TRILINOS_INSTALL_DIR=/usr/local/trilinos/MPI_REL
else
   echo "Usage: $0 -d (debug)"
   echo "Usage: $0 -r (release)"
   exit 1
fi

export ALBANY_HOME=/Users/gahanse/Codes/Albany
export ALB_FLAGS="-Wno-deprecated-declarations"
export ALB_ENABLE_UNIT_TESTS=ON
export ALB_ENABLE_LANDICE=ON
export ALB_ENABLE_MPAS=ON
export ALB_DEBUG=OFF
export ALB_ENABLE_CHECK_FPE=ON
export ALB_FLUSH_DENORMALS=OFF
export ALB_ENABLE_SPECULATIVE=OFF
export ALB_ENABLE_PERF_TESTS=ON
export ALB_VERBOSE=OFF

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH="$TRILINOS_INSTALL_DIR" \
      -D ENABLE_UNIT_TESTS:BOOL=${ALB_ENABLE_UNIT_TESTS} \
      -D ENABLE_LANDICE:BOOL=${ALB_ENABLE_LANDICE} \
      -D ENABLE_MPAS_INTERFACE=${ALB_ENABLE_MPAS} \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=${ALB_VERBOSE} \
      -D ENABLE_DEBUGGING:BOOL=${ALB_DEBUG} \
      -D ENABLE_CHECK_FPE:BOOL=${ALB_ENABLE_CHECK_FPE} \
      -D ENABLE_STRONG_FPE_CHECK:BOOL=${ALB_ENABLE_CHECK_FPE} \
      -D ENABLE_FLUSH_DENORMALS:BOOL=${ALB_FLUSH_DENORMALS} \
      -D ALBANY_CTEST_TIMEOUT:INTEGER=70 \
      -D CMAKE_MACOSX_RPATH:BOOL=ON \
      -D CMAKE_INSTALL_RPATH:PATH=/usr/local/openmpi-4.0.2/lib \
\
${ALBANY_HOME}

