save all

traction_x_1 = COHESIVE_TRACTION_01
traction_y_1 = COHESIVE_TRACTION_02
traction_z_1 = COHESIVE_TRACTION_03

traction_x_2 = COHESIVE_TRACTION_04
traction_y_2 = COHESIVE_TRACTION_05
traction_z_2 = COHESIVE_TRACTION_06

traction_x_3 = COHESIVE_TRACTION_07
traction_y_3 = COHESIVE_TRACTION_08
traction_z_3 = COHESIVE_TRACTION_09

traction_x_4 = COHESIVE_TRACTION_10
traction_y_4 = COHESIVE_TRACTION_11
traction_z_4 = COHESIVE_TRACTION_12

delete COHESIVE_TRACTION_01, COHESIVE_TRACTION_02, COHESIVE_TRACTION_03, COHESIVE_TRACTION_04
delete COHESIVE_TRACTION_05, COHESIVE_TRACTION_06, COHESIVE_TRACTION_07, COHESIVE_TRACTION_08
delete COHESIVE_TRACTION_09, COHESIVE_TRACTION_10, COHESIVE_TRACTION_11, COHESIVE_TRACTION_12

exit
