save all

traction_x_1 = COHESIVE_TRACTION_1_1
traction_y_1 = COHESIVE_TRACTION_2_1
traction_z_1 = COHESIVE_TRACTION_3_1

traction_x_2 = COHESIVE_TRACTION_1_2
traction_y_2 = COHESIVE_TRACTION_2_2
traction_z_2 = COHESIVE_TRACTION_3_2

traction_x_3 = COHESIVE_TRACTION_1_3
traction_y_3 = COHESIVE_TRACTION_2_3
traction_z_3 = COHESIVE_TRACTION_3_3

traction_x_4 = COHESIVE_TRACTION_1_4
traction_y_4 = COHESIVE_TRACTION_2_4
traction_z_4 = COHESIVE_TRACTION_3_4

delete COHESIVE_TRACTION_1_1, COHESIVE_TRACTION_2_1, COHESIVE_TRACTION_3_1, COHESIVE_TRACTION_1_2
delete COHESIVE_TRACTION_2_2, COHESIVE_TRACTION_3_2, COHESIVE_TRACTION_1_3, COHESIVE_TRACTION_2_3
delete COHESIVE_TRACTION_3_3, COHESIVE_TRACTION_1_4, COHESIVE_TRACTION_2_4, COHESIVE_TRACTION_3_4

exit
