#!/bin/bash -xe

#-------------------------------------------
#
# Prototype script to checkout, compile Dakota
#
#
# BvBW  10/06/08
# AGS  04/09
#-------------------------------------------

#-------------------------------------------
# setup and housekeeping
#-------------------------------------------

DUMMY1=${TRIKOTADIR:?TRIKOTADIR: not set}

\rm -rf dakota-.src.tar*

DLDIR=`pwd`

#-------------------------------------------
# copy, configure, build, install Dakota
#-------------------------------------------
TARBALL=dakota-stable.src.tar.gz

wget -nv --no-check-certificate \
    https://development.sandia.gov/dakota/distributions/dakota/stable/$TARBALL

cd $TRIKOTADIR

tar xzf $DLDIR/$TARBALL

\rm -rf Dakota
mv dakota-*.src Dakota

\rm $DLDIR/$TARBALL
