#!/bin/bash

#-------------------------------------------
#
# Prototype script to checkout, compile Dakota
#
#
# BvBW  10/06/08
# AGS  04/09
#-------------------------------------------

#-------------------------------------------
# setup and housekeeping
#-------------------------------------------

set -e

DUMMY1=${TRIKOTADIR:?TRIKOTADIR: not set}

if [ -a $dakota-stable.src.tar ]; then \rm $dakota-stable.src.tar
fi
if [ -a $dakota-stable.src.tar.gz ]; then \rm $dakota-stable.src.tar.gz
fi

DLDIR=`pwd`

#-------------------------------------------
# copy, configure, build, install Dakota
#-------------------------------------------

wget -nv --no-check-certificate \
 https://development.sandia.gov/dakota/distributions/dakota/stable/dakota-stable.src.tar.gz
gunzip dakota-stable.src.tar.gz

cd $TRIKOTADIR

tar xf $DLDIR/dakota-stable.src.tar

\rm -rf Dakota
mv dakota-*.src Dakota

\rm $DLDIR/dakota-stable.src.tar
