#!/bin/bash
# SCORPIO build script
BASE_DIR=/projects/albany/nightlyCDashAlbanyBlake
mkdir -p ${BASE_DIR}/build-gcc/ScoBuildReleaseGcc
cd ${BASE_DIR}/build-gcc/ScoBuildReleaseGcc

rm -rf CMake*

SCORPIO_SRC=${BASE_DIR}/repos-gcc/E3SM.MALI.dev/externals/scorpio
SCORPIO_INSTALL=${BASE_DIR}/build-gcc/ScorpioReleaseInstallGcc
CC=mpicc
CXX=mpicxx
FC=mpif90

cmake \
  -D CMAKE_INSTALL_PREFIX:PATH=${SCORPIO_INSTALL} \
  -D PnetCDF_PATH=${PARALLEL_NETCDF_ROOT} \
  -D NetCDF_C_PATH=${NETCDF_C_ROOT} \
  -D NetCDF_Fortran_PATH=${NETCDF_FORTRAN_ROOT} \
  -D PIO_ENABLE_TIMING=OFF \
${SCORPIO_SRC}

make -j 96
make install
cd ${BASE_DIR}

