#!/bin/bash
# Albany configure script on blake

rm -rf CMake*

cmake \
    -DALBANY_TRILINOS_DIR:FILEPATH=/home/projects/albany/nightlyCDashTrilinosBlake/build-intel/TrilinosSerialInstall \
    -DENABLE_LANDICE:BOOL=ON \
    -DENABLE_DEMO_PDES:BOOL=ON \
    -DENABLE_KOKKOS_UNDER_DEVELOPMENT:BOOL=ON \
    -DALBANY_CTEST_TIMEOUT=500 \
    -DENABLE_CHECK_FPE:BOOL=OFF \
    -DALBANY_MPI_EXEC_TRAILING_OPTIONS='--map-by ppr:1:core:pe=4' \
    -DENABLE_FAD_TYPE:STRING='SFad' \
    -DALBANY_SFAD_SIZE=12 \
    -DDISABLE_ALBANY_TESTS:BOOL=ON \
..

#For debug build:
#  -D CMAKE_CXX_FLAGS:STRING="-g -G" \
#  -g is for host code, -G is for device code
#
