#!/bin/bash
# This is a sample Trilinos configuration script for Albany on blake

rm -rf CMake*

PWD=`pwd`
INSTALL_DIR=$PWD/install

MPI_PATH=${MPI_ROOT}
MKL_PATH=${MKL_ROOT}
SUPERLU_PATH=${SUPERLU_ROOT}
BOOST_PATH=${BOOST_ROOT}
NETCDF_PATH=${NETCDF_ROOT}
PNETCDF_PATH=${PNETCDF_ROOT}
HDF5_PATH=${HDF5_ROOT}
ZLIB_PATH=${ZLIB_ROOT}

cmake \
    -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_DIR} \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
\
    -D CMAKE_CXX_COMPILER=mpicxx \
    -D CMAKE_C_COMPILER=mpicc \
    -D CMAKE_Fortran_COMPILER=mpif90 \
    -D CMAKE_C_FLAGS:STRING='-mkl' \
    -D CMAKE_CXX_FLAGS:STRING='-mkl' \
    -D CMAKE_Fortran_FLAGS:STRING='-mkl' \
    -D CMAKE_EXE_LINKER_FLAGS='-mkl' \
\
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D TPL_MPI_INCLUDE_DIRS:STRING=${MPI_PATH}/include \
    -D TPL_MPI_LIBRARY_DIRS:STRING=${MPI_PATH}/lib \
\
    -D TPL_ENABLE_BLAS:BOOL=ON \
    -D TPL_BLAS_LIBRARIES:STRING=${MKL_PATH}/lib/intel64/libmkl_core.a \
    -D TPL_ENABLE_LAPACK:BOOL=ON \
    -D TPL_LAPACK_LIBRARIES:STRING=${MKL_PATH}/lib/intel64/libmkl_core.a \
    -D TPL_ENABLE_SuperLU:BOOL=ON \
    -D TPL_SuperLU_LIBRARIES:PATH=${SUPERLU_PATH}/lib/libsuperlu.a \
    -D SuperLU_INCLUDE_DIRS:PATH=${SUPERLU_PATH}/include \
    -D TPL_ENABLE_PARDISO_MKL:BOOL=ON \
    -D TPL_PARDISO_MKL_LIBRARIES:PATH=${MKL_PATH}/lib/intel64/libmkl_intel_lp64.a \
    -D PARDISO_MKL_INCLUDE_DIRS:PATH=${MKL_PATH}/include \
\
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D Boost_INCLUDE_DIRS:PATH=${BOOST_PATH}/include \
    -D Boost_LIBRARY_DIRS:PATH=${BOOST_PATH}/lib \
    -D TPL_ENABLE_BoostLib:BOOL=ON \
    -D BoostLib_INCLUDE_DIRS:PATH=${BOOST_PATH}/include \
    -D BoostLib_LIBRARY_DIRS:PATH=${BOOST_PATH}/lib \
\
    -D TPL_ENABLE_Netcdf:BOOL=ON \
    -D Netcdf_INCLUDE_DIRS:PATH=${NETCDF_PATH}/include \
    -D Netcdf_LIBRARY_DIRS:PATH=${NETCDF_PATH}/lib \
    -D TPL_Netcdf_PARALLEL:BOOL=ON \
\
    -D TPL_ENABLE_Pnetcdf:BOOL=ON \
    -D Pnetcdf_INCLUDE_DIRS:PATH=${PNETCDF_PATH}/include \
    -D Pnetcdf_LIBRARY_DIRS:PATH=${PNETCDF_PATH}/lib \
\
    -D TPL_ENABLE_HDF5:STRING=ON \
    -D HDF5_INCLUDE_DIRS:PATH=${HDF5_PATH}/include \
    -D HDF5_LIBRARY_DIRS:PATH=${HDF5_PATH}/lib \
\
    -D TPL_ENABLE_Zlib:BOOL=ON \
    -D Zlib_INCLUDE_DIRS:PATH=${ZLIB_PATH}/include \
    -D Zlib_LIBRARY_DIRS:PATH=${ZLIB_PATH}/lib \
\
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
\
    -D TPL_ENABLE_Matio=OFF \
    -D TPL_ENABLE_SimMesh=OFF \
    -D TPL_ENABLE_SimModel=OFF \
    -D TPL_ENABLE_X11=OFF \
    -D TPL_ENABLE_Thrust:BOOL=OFF \
    -D TPL_ENABLE_CUDA:BOOL=OFF \
    -D TPL_ENABLE_CUSPARSE:BOOL=OFF \
\
    -D Kokkos_ARCH_SKX:BOOL=ON \
    -D Kokkos_ENABLE_CUDA_LAMBDA:BOOL=OFF \
    -D Kokkos_ENABLE_CUDA_UVM:BOOL=OFF \
    -D Kokkos_ENABLE_EXAMPLES:BOOL=OFF \
    -D Kokkos_ENABLE_OPENMP:BOOL=OFF \
    -D Kokkos_ENABLE_PTHREAD:BOOL=OFF \
    -D Kokkos_ENABLE_SERIAL:BOOL=ON \
    -D Kokkos_ENABLE_TESTS:BOOL=OFF \
\
    -D Amesos2_ENABLE_KLU2:BOOL=ON \
    -D Anasazi_ENABLE_RBGen:BOOL=OFF \
    -D EpetraExt_USING_HDF5:BOOL=OFF \
    -D Intrepid_ENABLE_TESTS:BOOL=OFF \
    -D Intrepid2_ENABLE_TESTS:BOOL=OFF \
    -D Phalanx_INDEX_SIZE_TYPE:STRING='INT' \
    -D Phalanx_KOKKOS_DEVICE_TYPE:STRING='SERIAL' \
    -D Phalanx_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
    -D Sacado_ENABLE_COMPLEX:BOOL=OFF \
    -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
    -D Tpetra_ASSUME_CUDA_AWARE_MPI:BOOL=OFF \
    -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
    -D Tpetra_INST_INT_INT:BOOL=OFF \
    -D Zoltan_ENABLE_ULONG_IDS:BOOL=ON \
\
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_Anasazi:BOOL=ON \
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack:BOOL=ON \
    -D Trilinos_ENABLE_Intrepid2:BOOL=ON \
    -D Trilinos_ENABLE_Kokkos:BOOL=ON \
    -D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
    -D Trilinos_ENABLE_KokkosContainers:BOOL=ON \
    -D Trilinos_ENABLE_KokkosCore:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D Trilinos_ENABLE_Pamgen:BOOL=ON \
    -D Trilinos_ENABLE_PanzerExprEval:BOOL=ON \
    -D Trilinos_ENABLE_Phalanx:BOOL=ON \
    -D Trilinos_ENABLE_Piro:BOOL=ON \
    -D Trilinos_ENABLE_ROL:BOOL=ON \
    -D Trilinos_ENABLE_SEACAS:BOOL=ON \
    -D Trilinos_ENABLE_SEACASAprepro_lib:BOOL=ON \
    -D Trilinos_ENABLE_SEACASExodus:BOOL=ON \
    -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
    -D Trilinos_ENABLE_STKDoc_tests:BOOL=OFF \
    -D Trilinos_ENABLE_STKIO:BOOL=ON \
    -D Trilinos_ENABLE_STKMesh:BOOL=ON \
    -D Trilinos_ENABLE_STKExprEval:BOOL=ON \
    -D Trilinos_ENABLE_Sacado:BOOL=ON \
    -D Trilinos_ENABLE_Shards:BOOL=ON \
    -D Trilinos_ENABLE_Stokhos:BOOL=OFF \
    -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
    -D Trilinos_ENABLE_TESTS:BOOL=OFF \
    -D Trilinos_ENABLE_Teko:BOOL=ON \
    -D Trilinos_ENABLE_Tempus:BOOL=ON \
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
    -D Trilinos_ENABLE_Thyra:BOOL=ON \
    -D Trilinos_ENABLE_ThyraTpetraAdapters:BOOL=ON \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
    -D Trilinos_ENABLE_TrilinosCouplings:BOOL=ON \
    -D Trilinos_ENABLE_TriKota:BOOL=OFF \
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan:BOOL=ON \
\
    -D Tpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
    -D Xpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF \
    -D Kokkos_ENABLE_LIBDL:BOOL=ON \
    -D Trilinos_ENABLE_PanzerDofMgr:BOOL=ON \
    -D Trilinos_ENABLE_ShyLU_DDFROSch:BOOL=ON \
    -D CMAKE_CXX_STANDARD=17 \
..
