#!/bin/bash -lxe
#this runs daily at 19:00 

cd /mscratch/albany/mayer/nightlyCDashJenkins
rm -rf * 
mkdir repos 

cd repos
cp -r ${WORKSPACE}/repos/Albany .
cp -r ${WORKSPACE}/repos/Trilinos .


export jenkins_albany_dir=/mscratch/albany/mayer/nightlyCDashJenkins/repos/Albany
export jenkins_trilinos_dir=/mscratch/albany/mayer/nightlyCDashJenkins/repos/Trilinos
export jenkins_trilinos_install_dir=/mscratch/albany/mayer/nightlyCDashJenkins/build/TrilinosInstall

cd ..

cp -r repos/Albany/doc/dashboards/mayer.sandia.gov/* .
cd jenkins
mv * ../
cd ..
rm -rf cron jenkins

bash -l -c "source mayer_arm_modules.sh >& modules_trilinos.out; bash nightly_cron_script_trilinos_mayer_jenkins.sh; sbatch batch.openmpi.bash"

chgrp wg-albany -R /mscratch/albany/mayer/nightlyCDashJenkins/*
chmod ug+rwX -R /mscratch/albany/mayer/nightlyCDashJenkins/*
