#! /bin/bash

# Here is a script for configuring Trilinos using cmake
# that includes the packages needed for Albany.
# Any environment variables (e.g. $BOOST_DIR) are
# set in the customization file, e.g. set_andy_env.in

SOURCE_DIR=${ALBDIR:-..}

cmake \
    -D ALBANY_TRILINOS_DIR:FILEPATH=$TRILINSTALLDIR \
    -D CMAKE_BUILD_TYPE:STRING=$ALBANY_BUILD_MODE \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=${ALBANY_VERBOSE_MAKEFILE:-OFF} \
    -D ALBANY_CXX_FLAGS:STRING="$ALBANY_CXX_FLAGS" \
    -D ENABLE_LCM:BOOL=${ALBANY_LCM:-OFF} \
    -D ENABLE_SG_MP:BOOL=${ALBANY_LCM:-OFF} \
    $SOURCE_DIR
