#! /bin/bash

# Here is a script for configuring Trilinos using cmake
# that includes the packages needed for Albany.
# Any environment variables (e.g. $BOOST_DIR) are
# set in the customization file, e.g. set_andy_env.in

# Need shell independence?
SOURCE_DIR=${TRILDIR:-..}
INSTALL_DIR=${TRILINSTALLDIR:-$(pwd)/install}

if [ $ALBANY_NEEDS_SUPERLU = "ON" ]
then
    SUPERLU_ARGS=" -D TPL_ENABLE_SuperLU:STRING=ON \
                   -D SuperLU_INCLUDE_DIRS:STRING=${SUPERLUDIR}/include \
                   -D SuperLU_LIBRARY_DIRS:STRING=${SUPERLUDIR}/lib"
else
    SUPERLU_ARGS=""
fi

cmake \
    -D Trilinos_DISABLE_ENABLED_FORWARD_DEP_PACKAGES=ON \
    -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR  \
    -D CMAKE_BUILD_TYPE:STRING=$TRILINOS_BUILD_TYPE  \
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
    -D Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=${TRILINOS_VERBOSE_MAKEFILE:-OFF} \
    -D BUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS:-OFF \
    -D CMAKE_CXX_FLAGS:STRING="$TRILINOS_CXX_FLAGS" \
\
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
    -D Teuchos_ENABLE_LONG_LONG_INT:BOOL=ON \
    -D Trilinos_ENABLE_Shards:BOOL=ON \
    -D Trilinos_ENABLE_Sacado:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    -D Amesos2_ENABLE_KLU2:BOOL=${TRILINOS_ENABLE_KLU2:-OFF} \
    -D Trilinos_ENABLE_Anasazi:BOOL=ON \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_Phalanx:BOOL=ON \
    -D Trilinos_ENABLE_Intrepid:BOOL=ON \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D Trilinos_ENABLE_Kokkos:BOOL=ON \
    -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
    -D Trilinos_ENABLE_Thyra:BOOL=ON \
    -D Trilinos_ENABLE_Rythmos:BOOL=ON \
    -D Trilinos_ENABLE_MOOCHO:BOOL=ON \
    -D Trilinos_ENABLE_Stokhos:BOOL=ON \
    -D Trilinos_ENABLE_Piro:BOOL=ON \
    -D Piro_ENABLE_TESTS:BOOL=ON \
    -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
    -D Trilinos_ENABLE_SEACASExodus:BOOL=ON \
    -D Trilinos_ENABLE_STKMesh:BOOL=ON \
    -D Trilinos_ENABLE_STKIO:BOOL=ON \
    -D Trilinos_ENABLE_Teko:BOOL=ON \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON \
    -D Trilinos_ENABLE_MueLu:BOOL=${ALBANY_NEEDS_MUELU:-OFF} \
\
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D TPL_ENABLE_BoostLib:BOOL=ON \
    -D Boost_INCLUDE_DIRS:FILEPATH=$BOOSTDIR/include \
    -D Boost_LIBRARY_DIRS:FILEPATH=$BOOSTDIR/lib \
    -D BoostLib_INCLUDE_DIRS:FILEPATH=$BOOSTDIR/include \
    -D BoostLib_LIBRARY_DIRS:FILEPATH=$BOOSTDIR/lib \
    -D TPL_ENABLE_Netcdf:BOOL=ON \
    -D Netcdf_INCLUDE_DIRS:PATH=$NETCDFDIR/include \
    -D Netcdf_LIBRARY_DIRS:PATH=$NETCDFDIR/lib \
    -D TPL_ENABLE_HDF5:BOOL=ON \
    -D HDF5_INCLUDE_DIRS:PATH=$HDF5DIR/include \
    -D HDF5_LIBRARY_DIRS:PATH=$HDF5DIR/lib \
    -D TPL_ENABLE_MPI:BOOL=ON \
    $SUPERLU_ARGS \
\
    $SOURCE_DIR
