#!/bin/bash
# Albany configure script on summitdev
rm -rf CMake*

# Point to Trilinos install path
TRILINOS_INSTALL=${HOME}/summitdev/Trilinos/build-serial/install

cmake \
    -DALBANY_TRILINOS_DIR:FILEPATH=${TRILINOS_INSTALL} \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
    -DENABLE_DEMO_PDES:BOOL=ON \
    -DENABLE_LANDICE:BOOL=ON \
    -DENABLE_ALBANY_EPETRA:BOOL=OFF \
    -DENABLE_LCM:BOOL=ON \
    -DENABLE_AERAS:BOOL=OFF \
    -DENABLE_ATO:BOOL=OFF \
    -DALBANY_LIBRARIES_ONLY=OFF \
    -DENABLE_KOKKOS_UNDER_DEVELOPMENT:BOOL=ON \
..

#For debug build:
#  -D CMAKE_CXX_FLAGS:STRING="-g -G" \
#  -g is for host code, -G is for device code
#
