#!/bin/bash
# Here is a script for configuring Trilinos using cmake
# that includes the packages needed for Albany/Aeras.
# Any environment variables should be set before 
# compiling (e.g. for the Ride cluster, use 
# ride_modules.sh or ride_modules_cuda60.sh).
# 

rm -rf CMake*

#FIXME: The following needs to be changed to point to your Trilinos! 
BUILD_DIR=`pwd`
TRIBUILDDIR=/home/jwatkin/Trilinos/build-kokkos-serial/
TRILINSTALLDIR=$TRIBUILDDIR/install

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH=$TRILINSTALLDIR \
      -D CMAKE_CXX_FLAGS:STRING="" \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -D ENABLE_DEMO_PDES:BOOL=OFF \
      -D ENABLE_FELIX:BOOL=OFF \
      -D ENABLE_QCAD:BOOL=OFF \
      -D ENABLE_LCM:BOOL=OFF \
      -D ENABLE_AERAS:BOOL=ON \
      -D ENABLE_SG:BOOL=OFF \
      -D ENABLE_ENSEMBLE:BOOL=OFF \
      -D ENABLE_STOKHOS:BOOL=OFF \
      -D ENABLE_ATO:BOOL=OFF \
      -D ENABLE_MOR:BOOL=OFF \
      -D ENABLE_PERFORMANCE_TESTS:BOOL=OFF \
      -D ALBANY_LIBRARIES_ONLY=OFF \
      -D ENABLE_INSTALL:BOOL=OFF \
      -D ENABLE_KOKKOS_UNDER_DEVELOPMENT:BOOL=ON \
..

#For debug build:
#  -D CMAKE_CXX_FLAGS:STRING="-g -G" \
#  -g is for host code, -G is for device code
#
