#!/bin/sh
#
export TRILINOS_HOME=/Users/gahanse/Codes/Trilinos
BUILD_DIR=`pwd`
INSTALL_DIR=/usr/local/trilinos/MPI_DBG
BOOST_DIR=/usr/local/openmpi-4.0.2
LIB_DIR=/usr/local/openmpi-4.0.2
MPI_BASE_DIR=/usr/local/openmpi-4.0.2
NETCDF=/usr/local/openmpi-4.0.2
HDFDIR=/usr/local/openmpi-4.0.2
PARMETISDIR=/usr/local/openmpi-4.0.2
SUPERLUDIR=/usr/local/openmpi-4.0.2/SuperLU_4.3

cmake \
    -Wno-dev \
\
    -D CMAKE_BUILD_TYPE:STRING=DEBUG \
    -D CMAKE_CXX_FLAGS:STRING="-g -O0 -Wno-inconsistent-missing-override" \
    -D Trilinos_CXX11_FLAGS:STRING="-std=c++11" \
    -D CMAKE_C_FLAGS:STRING="-g -O0 " \
    -D CMAKE_Fortran_FLAGS:STRING="-g -O0 -Wa,-q" \
    -D Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
    -D CMAKE_MACOSX_RPATH:BOOL=ON \
    -D CMAKE_INSTALL_RPATH:PATH=${MPI_BASE_DIR}/lib \
	-D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
    -D Trilinos_EXTRA_LINK_FLAGS:STRING="-L/usr/local/lib -L${LIB_DIR}/lib -lnetcdf -lpnetcdf -lhdf5_hl -lhdf5 -lz -Wl,-rpath,${LIB_DIR}/lib:/usr/local/lib" \
    -D CMAKE_C_ARCHIVE_CREATE:STRING="<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>" \
    -D CMAKE_CXX_ARCHIVE_CREATE:STRING="<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>" \
    -D CMAKE_Fortran_ARCHIVE_CREATE:STRING="<CMAKE_AR> Scr <TARGET> <LINK_FLAGS> <OBJECTS>" \
    -D CMAKE_C_ARCHIVE_FINISH:STRING="<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>" \
    -D CMAKE_CXX_ARCHIVE_FINISH:STRING="<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>" \
    -D CMAKE_Fortran_ARCHIVE_FINISH:STRING="<CMAKE_RANLIB> -no_warning_for_no_symbols -c <TARGET>" \
\
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_SECONDARY_TESTED_CODE:BOOL=ON \
    -D Trilinos_ENABLE_TESTS:BOOL=OFF \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
    -D Trilinos_ASSERT_MISSING_PACKAGES:BOOL=OFF \
\
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    -D Amesos2_ENABLE_KLU2:BOOL=ON \
    -D Trilinos_ENABLE_Anasazi:BOOL=ON \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    -D Trilinos_ENABLE_Intrepid2:BOOL=ON \
\
    -D Trilinos_ENABLE_ROL:BOOL=ON \
    -D Trilinos_ENABLE_MiniTensor:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
    -D MueLu_ENABLE_Tutorial:BOOL=OFF \
    -D Trilinos_ENABLE_Moertel:BOOL=OFF \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D Trilinos_ENABLE_Rythmos:BOOL=ON \
    -D Trilinos_ENABLE_Sacado:BOOL=ON \
    -D Trilinos_ENABLE_SCOREC:BOOL=ON \
    -D Trilinos_ENABLE_SEACAS:BOOL=ON \
    -D Trilinos_ENABLE_Shards:BOOL=ON \
    -D Trilinos_ENABLE_Stokhos:BOOL=ON \
    -D Trilinos_ENABLE_STK:BOOL=ON \
    -D Trilinos_ENABLE_STKSearch:BOOL=ON \
    -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack:BOOL=ON \
    -D Trilinos_ENABLE_Isorropia:BOOL=ON \
    -D Trilinos_ENABLE_Pamgen:BOOL=ON \
    -D Trilinos_ENABLE_Phalanx:BOOL=ON \
    -D Trilinos_ENABLE_Piro:BOOL=ON \
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
    -D Trilinos_ENABLE_Teko:BOOL=ON \
    -D Trilinos_ENABLE_Tempus:BOOL=ON \
    -D Trilinos_ENABLE_Thyra:BOOL=ON \
    -D Trilinos_ENABLE_Zoltan:BOOL=ON \
\
    -D Rythmos_ENABLE_DEBUG:BOOL=ON \
    -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
    -D Tpetra_INST_INT_LONG:BOOL=OFF \
    -D Tpetra_INST_INT_INT:BOOL=OFF \
    -D Tpetra_INST_DOUBLE:BOOL=ON \
    -D Tpetra_INST_FLOAT:BOOL=OFF \
    -D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
    -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
    -D Tpetra_INST_INT_UNSIGNED:BOOL=OFF \
    -D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=OFF \
    -D Zoltan_ENABLE_ULONG_IDS:BOOL=ON \
    -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
    -D ZOLTAN_BUILD_ZFDRIVE:BOOL=OFF \
    -D Phalanx_INDEX_SIZE_TYPE:STRING="KOKKOS" \
    -D Kokkos_ENABLE_Serial:BOOL=ON \
    -D Kokkos_ENABLE_OpenMP:BOOL=OFF \
    -D Kokkos_ENABLE_Pthread:BOOL=OFF \
\
    -D SEACAS_ENABLE_SEACASSVDI:BOOL=OFF \
    -D Trilinos_ENABLE_SEACASFastq:BOOL=OFF \
    -D Trilinos_ENABLE_SEACASBlot:BOOL=OFF \
    -D Trilinos_ENABLE_SEACASPLT:BOOL=OFF \
    -D TPL_ENABLE_X11:BOOL=OFF \
    -D TPL_ENABLE_Matio:BOOL=OFF \
\
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
\
	-D TPL_ENABLE_Pthread:BOOL=OFF \
\
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D TPL_ENABLE_BoostLib:BOOL=ON \
    -D TPL_ENABLE_BoostAlbLib:BOOL=ON \
	-D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
	-D BoostLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D BoostLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
	-D BoostAlbLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D BoostAlbLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
\
    -D TPL_Netcdf_PARALLEL:BOOL=ON \
    -D TPL_ENABLE_Netcdf:STRING=ON \
	-D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
	-D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
	-D TPL_ENABLE_Pnetcdf:BOOL=ON \
	-D Pnetcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
	-D Pnetcdf_LIBRARY_DIRS=$NETCDF/lib \
\
    -D TPL_ENABLE_HDF5:STRING=ON \
    -D HDF5_INCLUDE_DIRS:PATH="${HDFDIR}/include" \
    -D HDF5_LIBRARY_DIRS:PATH="${HDFDIR}/lib" \
\
    -D TPL_ENABLE_Zlib:STRING=ON \
    -D Zlib_INCLUDE_DIRS:PATH=$LIB_DIR/include \
    -D Zlib_LIBRARY_DIRS:PATH=$LIB_DIR/lib \
\
    -D TPL_ENABLE_SuperLU:STRING=ON \
    -D SuperLU_INCLUDE_DIRS:STRING="${SUPERLUDIR}/include" \
    -D SuperLU_LIBRARY_DIRS:STRING="${SUPERLUDIR}/lib" \
\
    -D TPL_ENABLE_BLAS:STRING=ON \
    -D TPL_ENABLE_LAPACK:STRING=ON \
    -D BLAS_LIBRARY_DIRS:STRING="/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current" \
    -D BLAS_INCLUDE_DIRS:STRING="/usr/local/openmpi-4.0.2/include" \
    -D LAPACK_LIBRARY_DIRS:STRING="/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current" \
    -D LAPACK_INCLUDE_DIRS:STRING="/usr/local/openmpi-4.0.2/include" \
\
    -D TPL_ENABLE_ParMETIS:STRING=ON \
    -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETISDIR}/include" \
    -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETISDIR}/lib" \
\
$EXTRA_ARGS \
${TRILINOS_HOME}

exit 0

    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit" \
    -D Trilinos_ENABLE_DataTransferKit:BOOL=OFF \
    -D Trilinos_ENABLE_DataTransferKitSTKMeshAdapters:BOOL=OFF \
    -D DataTransferKit_ENABLE_DBC:BOOL=OFF \
    -D Tpetra_INST_INT_UNSIGNED_LONG:BOOL=ON \
