#!/bin/sh
#
export TRILINOS_HOME=/Users/gahanse/Codes/Trilinos
BUILD_DIR=`pwd`
INSTALL_DIR=/usr/local/trilinos/MPI_DBG64
BOOST_DIR=/usr/local/mpich-3.1.4
LIB_DIR=/usr/local/mpich-3.1.4
MPI_BASE_DIR=/usr/local/mpich-3.1.4
NETCDF=/usr/local/mpich-3.1.4
HDFDIR=/usr/local/mpich-3.1.4
PARMETISDIR=/usr/local/mpich-3.1.4
#SUPERLUDIR=/usr/local/mpich-3.1.4/SuperLU_5.2.1 # Wrong # arguments for
SUPERLUDIR=/usr/local/mpich-3.1.4/SuperLU_4.3

cmake \
    -Wno-dev \
    -D Trilinos_CONFIGURE_OPTIONS_FILE:FILEPATH=$TRILINOS_HOME/sampleScripts/AlbanySettings.cmake \
    -D Trilinos_ENABLE_SCOREC:BOOL=ON \
    -D Trilinos_ENABLE_DataTransferKit:BOOL=ON \
    -D SCOREC_DISABLE_STRONG_WARNINGS:BOOL=ON \
    -D CMAKE_BUILD_TYPE:STRING=NONE \
    -D Trilinos_SHOW_DEPRECATED_WARNINGS:BOOL=OFF \
    -D CMAKE_CXX_FLAGS:STRING="-g -O0 -DNDEBUG -Wno-inconsistent-missing-override" \
    -D Trilinos_CXX11_FLAGS:STRING="-std=c++11 -DNDEBUG " \
    -D CMAKE_C_FLAGS:STRING="-g -O0 -DNDEBUG " \
    -D CMAKE_Fortran_FLAGS:STRING="-g -O0 -Wa,-q -DNDEBUG" \
    -D Rythmos_ENABLE_DEBUG:BOOL=ON \
    -D Trilinos_ENABLE_ThyraTpetraAdapters:BOOL=ON \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Tpetra_INST_INT_LONG_LONG:BOOL=ON \
    -D Tpetra_INST_INT_INT:BOOL=OFF \
    -D MueLu_ENABLE_Epetra:BOOL=OFF \
    -D MueLu_ENABLE_EpetraExt:BOOL=OFF \
    -D MueLu_INST_FLOAT_INT_INT:BOOL=OFF \
    -D MueLu_INST_DOUBLE_INT_INT:BOOL=OFF \
    -D Tpetra_INST_DOUBLE:BOOL=ON \
    -D Tpetra_INST_FLOAT:BOOL=OFF \
    -D Tpetra_INST_COMPLEX_FLOAT:BOOL=OFF \
    -D Tpetra_INST_COMPLEX_DOUBLE:BOOL=OFF \
    -D Tpetra_INST_INT_LONG:BOOL=ON \
    -D Tpetra_INST_INT_UNSIGNED:BOOL=OFF \
    -D Zoltan_ENABLE_ULONG_IDS:BOOL=ON \
    -D MDS_ID_TYPE:STRING="long int" \
    -D Teuchos_ENABLE_LONG_LONG_INT:BOOL=ON \
    -D Teuchos_ENABLE_COMPLEX:BOOL=OFF \
    -D ZOLTAN_BUILD_ZFDRIVE:BOOL=OFF \
    -D Trilinos_ENABLE_Kokkos:BOOL=ON \
    -D Trilinos_ENABLE_KokkosCore:BOOL=ON \
    -D Phalanx_KOKKOS_DEVICE_TYPE:STRING="SERIAL" \
    -D Phalanx_INDEX_SIZE_TYPE:STRING="LONGINT" \
    -D Kokkos_ENABLE_Serial:BOOL=ON \
    -D Kokkos_ENABLE_OpenMP:BOOL=OFF \
    -D Kokkos_ENABLE_Pthread:BOOL=OFF \
    -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
\
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
\
    -D TPL_ENABLE_Matio:BOOL=OFF \
\
    -D TPL_ENABLE_MPI:BOOL=ON \
    -D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
\
	-D TPL_ENABLE_Pthread:BOOL=OFF \
\
    -D TPL_ENABLE_Boost:BOOL=ON \
    -D TPL_ENABLE_BoostLib:BOOL=ON \
    -D TPL_ENABLE_BoostAlbLib:BOOL=ON \
	-D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
	-D BoostLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D BoostLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
	-D BoostAlbLib_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D BoostAlbLib_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
\
    -D CMAKE_MACOSX_RPATH:BOOL=ON \
    -D CMAKE_INSTALL_RPATH:PATH=${MPI_BASE_DIR}/lib \
\
    -D TPL_Netcdf_PARALLEL:BOOL=ON \
    -D TPL_ENABLE_Netcdf:STRING=ON \
	-D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
	-D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
\
    -D TPL_ENABLE_HDF5:STRING=ON \
    -D HDF5_INCLUDE_DIRS:PATH="${HDFDIR}/include" \
    -D TPL_HDF5_LIBRARIES:PATH="${HDFDIR}/lib/libhdf5_hl.a;${HDFDIR}/lib/libhdf5.a;${LIB_DIR}/lib/libz.a" \
\
    -D TPL_ENABLE_Zlib:STRING=ON \
    -D Zlib_INCLUDE_DIRS:PATH=$LIB_DIR/include \
    -D TPL_Zlib_LIBRARIES:PATH="$LIB_DIR/lib/libz.a" \
\
    -D TPL_ENABLE_SuperLU:STRING=ON \
    -D SuperLU_INCLUDE_DIRS:STRING="${SUPERLUDIR}/include" \
    -D SuperLU_LIBRARY_DIRS:STRING="${SUPERLUDIR}/lib" \
\
    -D TPL_ENABLE_BLAS:STRING=ON \
    -D TPL_ENABLE_LAPACK:STRING=ON \
    -D BLAS_INCLUDE_DIRS:STRING="/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers" \
    -D BLAS_LIBRARY_DIRS:STRING="/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current" \
    -D LAPACK_INCLUDE_DIRS:STRING="/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers" \
    -D LAPACK_LIBRARY_DIRS:STRING="/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current" \
\
    -D TPL_ENABLE_ParMETIS:STRING=ON \
    -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETISDIR}/include" \
    -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETISDIR}/lib" \
\
	-D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
    -D Trilinos_EXTRA_LINK_FLAGS:STRING="-L${HDFDIR}/lib -L${LIB_DIR}/lib -lnetcdf -lhdf5_hl -lhdf5 -lz" \
\
    -D Trilinos_ENABLE_Moertel:BOOL=OFF \
    -D Moertel_ENABLE_EXAMPLES:BOOL=OFF \
    -D Moertel_ENABLE_Morkon:BOOL=OFF \
    -D Trilinos_ENABLE_TriKota:BOOL=OFF \
    -D Trilinos_ENABLE_Intrepid2:BOOL=ON \
    -D Trilinos_ENABLE_Intrepid:BOOL=OFF \
    -D Trilinos_ENABLE_SECONDARY_TESTED_CODE=OFF \
\
$EXTRA_ARGS \
${TRILINOS_HOME}

exit 0
