#!/bin/bash

#To build Trilinos on Hopper: 
#`1.) source hopper_modules.sh 
# 2.) source hopper-albany-cmake 
# 3.) make -j 8 
# 4.) make install -j 8 



rm -f CMakeCache.txt

cmake -D CMAKE_INSTALL_PREFIX:PATH=/global/project/projectdirs/piscees/trilinos/trilinos-albany-build/install \
      -D Boost_INCLUDE_DIRS:FILEPATH="${BOOST_DIR}/include" \
      -D BoostLib_INCLUDE_DIRS:FILEPATH="${BOOST_DIR}/include" \
      -D Netcdf_LIBRARY_DIRS:FILEPATH="${NETCDF_DIR}/lib" \
      -D Netcdf_INCLUDE_DIRS:FILEPATH="${NETCDF_DIR}/include" \
      -D CMAKE_BUILD_TYPE:STRING=RELEASE \
      -D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
      -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
      -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
\
      -D Trilinos_ENABLE_Fortran:BOOL=ON \
\
      -D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
      -D Trilinos_ENABLE_Teuchos:BOOL=ON \
      -D HAVE_TEUCHOS_COMM_TIMERS=ON \
      -D Trilinos_ENABLE_Shards:BOOL=ON \
      -D Trilinos_ENABLE_Sacado:BOOL=ON \
      -D Trilinos_ENABLE_Epetra:BOOL=ON \
      -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
      -D Trilinos_ENABLE_Ifpack:BOOL=ON \
      -D Trilinos_ENABLE_AztecOO:BOOL=ON \
      -D Trilinos_ENABLE_Amesos:BOOL=ON \
      -D Trilinos_ENABLE_Anasazi:BOOL=ON \
      -D Trilinos_ENABLE_Belos:BOOL=ON \
      -D Trilinos_ENABLE_Phalanx:BOOL=ON \
      -D Trilinos_ENABLE_Intrepid:BOOL=ON \
      -D Trilinos_ENABLE_ML:BOOL=ON \
      -D Trilinos_ENABLE_NOX:BOOL=ON \
      -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
      -D Trilinos_ENABLE_Thyra:BOOL=ON \
      -D Trilinos_ENABLE_Rythmos:BOOL=ON \
      -D Trilinos_ENABLE_MOOCHO:BOOL=ON \
      -D Trilinos_ENABLE_OptiPack:BOOL=ON \
      -D Trilinos_ENABLE_GlobiPack:BOOL=ON \
      -D Trilinos_ENABLE_Stokhos:BOOL=ON \
      -D Trilinos_ENABLE_Isorropia:BOOL=ON\
      -D Trilinos_ENABLE_Piro:BOOL=ON \
      -D Trilinos_ENABLE_STKIO:BOOL=ON \
      -D Trilinos_ENABLE_STKMesh:BOOL=ON \
      -D Trilinos_ENABLE_SEACASExodus:BOOL=ON \
      -D Trilinos_ENABLE_Teko:BOOL=ON \
\
      -D Trilinos_ENABLE_TriKota:BOOL=OFF \
      -D TriKota_ENABLE_DakotaCMake:BOOL=OFF \
      -D DAKOTA_ENABLE_TESTS:BOOL=OFF \
      -D Boost_LIBRARY_DIRS:FILEPATH="${BOOST_DIR}/lib" \
      -D BoostLib_LIBRARY_DIRS:FILEPATH="${BOOST_DIR}/lib" \
\
      -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
      -D Trilinos_ENABLE_ThreadPool:STRING="ON" \
      -D Trilinos_ENABLE_Pamgen:BOOL=ON \
      -D TPL_ENABLE_Netcdf:BOOL=ON \
      -D TPL_Netcdf_INCLUDE_DIRS:PATH="${NETCDF_DIR}/include" \
      -D Netcdf_LIBRARY_DIRS:PATH="${NETCDF_DIR}/lib" \
\
      -D Trilinos_ENABLE_Mesquite:BOOL=OFF\
      -D Trilinos_ENABLE_Zoltan:BOOL=ON \
      -D Trilinos_ENABLE_FEI:BOOL=OFF\
\
      -D Trilinos_ENABLE_TESTS:BOOL=OFF \
      -D Piro_ENABLE_TESTS:BOOL=OFF \
      -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
      -D TPL_ENABLE_MPI:BOOL=ON \
      -D TPL_ENABLE_Boost:BOOL=ON \
      -D TPL_ENABLE_BoostLib:BOOL=ON \
\
      -D Anasazi_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D AztecOO_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Belos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Ifpack_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D NOX_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Phalanx_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=OFF \
      -D Rythmos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Stokhos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Stratimikos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Thyra_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
      -D Trilinos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
\
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
      -D CMAKE_CXX_FLAGS:STRING="-O2" \
      -D CMAKE_Fortran_FLAGS:STRING="-O2" \
      -D Trilinos_ENABLE_Export_Makefiles:BOOL=ON \
\
      -D CMAKE_C_COMPILER:FILEPATH="cc" \
      -D CMAKE_CXX_COMPILER:FILEPATH="CC" \
      -D CMAKE_Fortran_COMPILER:FILEPATH="ftn" \
      -D TPL_BLAS_LIBRARIES:STRING="sci_gnu_mp" \
      -D TPL_LAPACK_LIBRARIES:STRING="sci_gnu_mp" \
      -DTPL_ENABLE_Pthread:BOOL=OFF \
      -DTPL_ENABLE_BinUtils:BOOL=OFF \
\
      -D MPI_EXEC:FILEPATH=aprun \
      -D MPI_EXEC_MAX_NUMPROCS:STRING=4 \
      -D MPI_EXEC_NUMPROCS_FLAG:STRING=-n \
\
..

#   -D Trilinos_ENABLE_Fortran:BOOL=OFF \
#   -D TPL_BLAS_LIBRARIES:STRING="-L${ACML_DIR}/lib -lacml -lpgmp -pgcpplibs -lz" \
#   -D TPL_LAPACK_LIBRARIES:STRING="-L${ACML_DIR}/lib -lacml -lpgmp -pgcpplibs -lz" \
#   -D CMAKE_Fortran_FLAGS:STRING="-Mconcur -mp" \
#   -D CMAKE_Fortran_FLAGS_DEBUG:STRING="-Mconcur -mp" \

