#!/bin/bash

#To configure Albany on Hopper: source this file 

#IK, 10/1/13
#prior to configuring you need to load the following modules: 
#module unload cmake netcdf-hdf5parallel/4.2.0 python
#module swap PrgEnv-pgi PrgEnv-gnu; module load cmake/2.8.7 python netcdf-hdf5parallel/4.2.0 usg-default-modules/1.0
#module load boost
#module list

rm CMakeCache.txt
cmake  \
    -D ALBANY_TRILINOS_DIR:FILEPATH="/project/projectdirs/piscees/trilinos/trilinos-albany-adapt-build/install" \
    
    -D ENABLE_DEMO_PDES=OFF -D ENABLE_SG=OFF -D ENABLE_ENSEMBLE=OFF -D ENABLE_MOR=OFF -DENABLE_QCAD=OFF  -DENABLE_ASCR=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D ENABLE_GPTL:BOOL=ON \
    -D ENABLE_LCM:BOOL=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D ALBANY_STK_PERCEPT=ON \
    -D GPTL_INCLUDE_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    -D GPTL_LIBRARY_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    ../albany-felix-src

