#!/bin/bash

#To build Albany on Hopper: 
#`1.) source hopper_modules.sh 
# 2.) source hopper-albany-cmake 
# 3.) make -j 8 


rm -f CMakeCache.txt
cmake  \
    -D ALBANY_TRILINOS_DIR:FILEPATH="/global/project/projectdirs/piscees/trilinos/trilinos-albany-build/install" \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -D ENABLE_DEMO_PDES=OFF -D ENABLE_SG=OFF  -D ENABLE_ENSEMBLE=OFF -D ENABLE_MOR=OFF -DENABLE_QCAD=OFF  -DENABLE_ASCR=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D ENABLE_GPTL:BOOL=ON \
    -D ENABLE_LCM:BOOL=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D GPTL_INCLUDE_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    -D GPTL_LIBRARY_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    ..

