#!/bin/bash -lxe


cd /mscratch/albany/mayer/nightlyCDashJenkins
rm -rf * 
mkdir repos 

cd repos
cp -r ${WORKSPACE}/repos/Albany .
cp -r ${WORKSPACE}/repos/Trilinos .


export jenkins_albany_dir=/mscratch/albany/mayer/nightlyCDashJenkins/repos/Albany
export jenkins_trilinos_dir=/mscratch/albany/mayer/nightlyCDashJenkins/repos/Trilinos
export jenkins_trilinos_install_dir=/mscratch/albany/mayer/nightlyCDashJenkins/build/TrilinosInstall

cd ..

cp repos/Albany/doc/dashboards/mayer.sandia.gov/* .


bash -l -c "source mayer_arm_modules.sh >& modules_trilinos.out; bash nightly_cron_script_trilinos_mayer_jenkins.sh"
bash -l -c "source mayer_arm_modules.sh >& modules_albany.out; bash nightly_cron_script_albany_mayer_jenkins.sh"

chgrp wg-albany -R /mscratch/albany/mayer/nightlyCDashJenkins/*
chmod ug+rwX -R /mscratch/albany/mayer/nightlyCDashJenkins/*
