#!/bin/bash
# This is a sample MPAS configuration script

PIO_DIR=
ALBANY_DIR=
TRILINOS_DIR=

# Get ALBANY_LINK_LIBS (Note: Need to add quotes to file)
source ${ALBANY_DIR}/export_albany.in

make clean \
  CORE=landice

make -j 16 gnu-nersc \
  CORE=landice \
  ALBANY=true \
  USE_PIO2=true \
  NETCDF=${NETCDF_DIR} \
  PNETCDF=${PARALLEL_NETCDF_DIR} \
  PIO=${PIO_DIR} \
  MPAS_EXTERNAL_LIBS="${ALBANY_LINK_LIBS} -Wl,-R${ALBANY_DIR}/lib -Wl,-R${TRILINOS_DIR}/lib -lstdc++ -L${CRAY_LIBSCI_PREFIX_DIR}/lib/libsci_gnu_mpi.a" \
  MPAS_EXTERNAL_INCLUDES="-I${ALBANY_DIR}/include -I${CRAY_LIBSCI_PREFIX_DIR}/include"

