cd "$LCM_DIR"
ln -s Albany/doc/LCM/build/env-single.sh .
ln -s Albany/doc/LCM/build/env-all.sh .
ln -s Albany/doc/LCM/build/trilinos-config.sh .
ln -s Albany/doc/LCM/build/albany-config.sh .
ln -s Albany/doc/LCM/build/build.sh .
ln -s Albany/doc/LCM/build/build-all.sh .
ln -s build.sh clean-config-build-test-dash.sh
ln -s build.sh clean-config-build-test.sh
ln -s build.sh config-build-test.sh
ln -s build.sh build-test.sh
ln -s build.sh test-dash.sh
ln -s build.sh test.sh
ln -s build.sh clean-config-build-dash.sh
ln -s build.sh clean-config-build.sh
ln -s build.sh config-build.sh
ln -s build.sh clean-config-dash.sh
ln -s build.sh clean-config.sh
ln -s build.sh config.sh
ln -s build.sh clean.sh
