#!/bin/bash
# This is a sample Albany configuration script

# Cleanup old cmake files
rm -rf CMake*

#FIXME: the following needs needs to be changed to point to your Trilinos! 
TRILINOS_INSTALL_DIR=
ALBANY_SRC_DIR=
ALBANY_INSTALL_DIR=

export CRAYPE_LINK_TYPE=static

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH=${TRILINOS_INSTALL_DIR} \
      -D CMAKE_INSTALL_PREFIX:PATH=${ALBANY_INSTALL_DIR} \
      -D CMAKE_CXX_FLAGS:STRING="-fPIC" \
      -D CMAKE_EXE_LINKER_FLAGS="-fPIC -ldl" \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -D ENABLE_DEMO_PDES:BOOL=OFF \
      -D ENABLE_LANDICE:BOOL=ON \
      -D ENABLE_MPAS_INTERFACE:BOOL=ON \
      -D ENABLE_MESH_DEPENDS_ON_PARAMETERS:BOOL=OFF \
      -D BUILD_SHARED_LIBS:BOOL=ON \
      -D Albany_BUILD_STATIC_EXE:BOOL=OFF \
      -D ENABLE_FAD_TYPE:STRING="SFad" \
      -D ALBANY_SFAD_SIZE=16 \
      -D ENABLE_MPAS_INTERFACE:BOOL=ON \
      ${ALBANY_SRC_DIR}

