#!/bin/bash

#To configure Albany on Hopper: source this file 

#IK, 10/1/13
#prior to configuring you need to load the following modules: 

rm -f CMakeCache.txt

cmake  \
    -D ALBANY_TRILINOS_DIR:FILEPATH=$TRILINSTALLDIR \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -D ENABLE_DEMO_PDES=OFF -D ENABLE_SG=OFF -D ENABLE_ENSEMBLE=OFF -D ENABLE_MOR=OFF -DENABLE_QCAD=OFF  -DENABLE_ASCR=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D ENABLE_GPTL:BOOL=OFF \
    -D ENABLE_LCM:BOOL=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D GPTL_INCLUDE_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    -D GPTL_LIBRARY_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    -D Albany_BUILD_STATIC_EXE:BOOL=ON \
    -D ALBANY_MPI_OPTIONS:BOOL=ON \
    -D ALBANY_MPI_EXEC:FILEPATH=aprun \
    -D ALBANY_MPI_EXEC_MAX_NUMPROCS:STRING=4 \
    -D ALBANY_MPI_EXEC_NUMPROCS_FLAG:STRING=-n \
    ..

