#!/bin/bash

#To build Albany on Hopper: 
#`1.) source hopper_modules.sh 
# 2.) source hopper-albany-cmake 
# 3.) make -j 8 


echo $TRILINSTALLDIR

rm -f CMakeCache.txt
cmake  \
    -D ALBANY_TRILINOS_DIR:FILEPATH=$TRILINSTALLDIR \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -D ENABLE_DEMO_PDES=OFF -D ENABLE_SG_MP=OFF -D ENABLE_MOR=OFF -DENABLE_QCAD=OFF  -DENABLE_ASCR=OFF \
    -D ENABLE_GPTL:BOOL=ON \
    -D ENABLE_LCM:BOOL=OFF \
    -D ENABLE_FELIX:BOOL=ON \
    -D ENABLE_INSTALL:BOOL=ON \
    -D CMAKE_INSTALL_PREFIX:PATH=$ALBINSTALLDIR \
    -D GPTL_INCLUDE_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    -D GPTL_LIBRARY_DIR:FILEPATH="/global/project/projectdirs/ccsm1/libgptl/newlibgptl-gnu" \
    -D ENABLE_CISM_INTERFACE:BOOL=ON \
    -D CISM_INCLUDE_DIR:FILEPATH=$CISMDIR/libdycore \
    -D Albany_BUILD_STATIC_EXE:BOOL=ON \
    -D ALBANY_MPI_OPTIONS:BOOL=ON \
    -D ALBANY_MPI_EXEC:FILEPATH=aprun \
    -D ALBANY_MPI_EXEC_MAX_NUMPROCS:STRING=4 \
    -D ALBANY_MPI_EXEC_NUMPROCS_FLAG:STRING=-n \
    ..

