
# What to build and test
set (CLEAN_BUILD FALSE)
set (DOWNLOAD_TRILINOS FALSE)
set (BUILD_TRILINOS_SERIAL FALSE)
set (DOWNLOAD_ALBANY FALSE) 
set (BUILD_ALBANY_SERIAL FALSE) 
set (RUN_ALBANY_SERIAL TRUE) 
