#include "PHAL_AlbanyTraits.hpp"

#include "LandIce_HydrologySurfaceWaterInput.hpp"
#include "LandIce_HydrologySurfaceWaterInput_Def.hpp"

PHAL_INSTANTIATE_TEMPLATE_CLASS_WITH_EXTRA_ARGS(LandIce::HydrologySurfaceWaterInput,true)
PHAL_INSTANTIATE_TEMPLATE_CLASS_WITH_EXTRA_ARGS(LandIce::HydrologySurfaceWaterInput,false)
