#!/bin/sh
#
# Here is a script for configuring Glen's working version of Albany
#
# Note: This heavily borrows ideas from Kevin Long's Trilinos configure script

# Parse for command line arguments
TEMP=`getopt -o x --long help,felix,mor,debug,lcm,qcad,speculative,hyd,scorec,dryrun,verbose,fpe,lameinc:,lamelib:,trilinos: -- "$@"`

eval set -- "$TEMP"

while true ; do
    case "$1" in
      --dryrun) ECHO=echo; shift;;
      --hyd) ALB_ENABLE_HYDRIDE=ON; shift ;;
      --lameinc)
             ALB_LAME_INC_DIR="$2"; shift 2;;
      --lamelib)
             ALB_LAME_LIB_DIR="$2"; shift 2;;
      --lcm) ALB_ENABLE_LCM=ON; shift ;;
      --qcad) ALB_ENABLE_QCAD=ON; shift ;;
      --speculative) ALB_ENABLE_SPECULATIVE=ON; shift ;;
      --scorec) ALB_ENABLE_SCOREC=ON; shift ;;
      --debug) ALB_DEBUG=ON; shift ;;
      --fpe) ALB_ENABLE_CHECK_FPE=ON; shift ;;
      --ascr) ALB_ENABLE_ASCR=ON; shift ;;
      --felix) ALB_ENABLE_FELIX=ON; shift ;;
      --mor) ALB_ENABLE_MOR=ON; shift ;;
      --albany_CI) ALB_ENABLE_AlbanyCI=ON; shift ;;
      --verbose) ALB_VERBOSE=ON; shift;;
      --trilinos)
            TRILINOS_INSTALL_DIR="$2"; shift 2;;
      --help)
            echo "Command-line arguments:"
            echo "--help             help"
            echo "--dryrun           print the command that would be used"
            echo "--verbose          enable verbose configuration (default: off)"
            echo "--lameinc  <dir>   set location of LAME include files (no default)"
            echo "--lamelib  <dir>   set location of LAME library files (no default)"
            echo "--lcm              enable LCM capabilities (default: off)"
            echo "--qcad             enable QCAD capabilities (default: off)"
            echo "--speculative      enable speculative code and capabilities (default: off)"
            echo "--hyd              enable Hydride capabilities (default: off)"
            echo "--scorec           enable RPI SCOREC adaptation (default: off)"
            echo "--ascr             enable ASCR capabilities (default: off)"
            echo "--felix            enable Land Ice SciDAC project code (default: off)"
            echo "--mor              enable Model Order Reduction (default: off)"
            echo "--debug            enable special debugging info and traps for floating point exceptions (default: off)"
            echo "--trilinos <dir>   set location of Trilinos library (no default)"
            echo " ";
            exit 0;
            shift
            ;;
      --) shift; break;;
   esac
done

if [ -z "$TRILINOS_INSTALL_DIR" ]; then
    echo -e "\nNeed to set environment variable TRILINOS_INSTALL_DIR or use --trilinos <dir> option"
    exit 1
fi

# LAME
if [ -z "$ALB_LAME_INC_DIR" -o  -z "$ALB_LAME_LIB_DIR" ]; then
  echo -e "\nLAME capabilities are NOT configured. If this is incorrect:"
  echo "Need to set environment variables ALB_LAME_* or use --lameinc <dir> and --lamelib <dir> options"
  ALB_ENABLE_LAME=OFF
else
  ALB_ENABLE_LAME=ON
fi

if [ -z "$ALB_ENABLE_HYDRIDE" -o "$ALB_ENABLE_HYDRIDE" = "OFF" ]; then
    echo -e "\nHydride capabilities are NOT configured. If this is incorrect, use option --hyd"
    ALB_ENABLE_HYDRIDE=OFF
fi

if [ -z "$ALB_ENABLE_LCM" -o "$ALB_ENABLE_LCM" = "OFF" ]; then
    echo -e "\nLCM capabilities are NOT configured. If this is incorrect, use option --lcm"
    ALB_ENABLE_LCM=OFF
fi

if [ -z "$ALB_ENABLE_QCAD" -o "$ALB_ENABLE_QCAD" = "OFF" ]; then
    echo -e "\nQCAD capabilities are NOT configured. If this is incorrect, use option --qcad"
    ALB_ENABLE_QCAD=OFF
fi

if [ -z "$ALB_ENABLE_SPECULATIVE" -o "$ALB_ENABLE_SPECULATIVE" = "OFF" ]; then
    echo -e "\nSpeculative code/capabilities are NOT configured. If this is incorrect, use option --speculative"
    ALB_ENABLE_SPECULATIVE=OFF
fi

if [ -z "$ALB_ENABLE_FELIX" -o "$ALB_ENABLE_FELIX" = "OFF" ]; then
    echo -e "\nFELIX capabilities are NOT configured. If this is incorrect, use option --felix"
    ALB_ENABLE_FELIX=OFF
fi

if [ -z "$ALB_ENABLE_MOR" -o "$ALB_ENABLE_MOR" = "OFF" ]; then
    echo -e "\nMOR capabilities are NOT configured. If this is incorrect, use option --mor"
    ALB_ENABLE_MOR=OFF
fi

if [ -z "$ALB_ENABLE_AlbanyCI" -o "$ALB_ENABLE_AlbanyCI" = "OFF" ]; then
    echo -e "\nAlbany CI capabilities are NOT configured. If this is incorrect, use option --albany_CI"
    ALB_ENABLE_AlbanyCI=OFF
fi

if [ -z "$ALB_ENABLE_ASCR" -o "$ALB_ENABLE_ASCR" = "OFF" ]; then
    echo -e "\nASCR capabilities are NOT configured. If this is incorrect, use option --ascr"
    ALB_ENABLE_ASCR=OFF
fi



if [ -z "$ALB_ENABLE_SCOREC" -o "$ALB_ENABLE_SCOREC" = "OFF" ]; then
    echo -e "\nSCOREC capabilities are NOT configured. If this is incorrect, use option --scorec"
    ALB_ENABLE_SCOREC=OFF
fi

if [ -z "$ALB_VERBOSE" -o "$ALB_VERBOSE" = "OFF" ]; then
    ALB_VERBOSE=OFF
fi

if [ -z "$ALB_DEBUG" -o "$ALB_DEBUG" = "OFF" ]; then
    ALB_DEBUG=OFF
fi

if [ -z "$ALB_ENABLE_CHECK_FPE" -o "$ALB_ENABLE_CHECK_FPE" = "OFF" ]; then
    ALB_ENABLE_CHECK_FPE=OFF
fi

echo -e "\n"

${ECHO} cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH="$TRILINOS_INSTALL_DIR" \
      -D ENABLE_LCM:BOOL=${ALB_ENABLE_LCM} \
      -D ENABLE_QCAD:BOOL=${ALB_ENABLE_QCAD} \
      -D ENABLE_LCM_SPECULATIVE:BOOL=${ALB_ENABLE_SPECULATIVE} \
      -D ENABLE_LAME:BOOL=${ALB_ENABLE_LAME} \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=${ALB_VERBOSE} \
      -D ENABLE_DEBUGGING:BOOL=${ALB_DEBUG} \
      -D ENABLE_CHECK_FPE:BOOL=${ALB_ENABLE_CHECK_FPE} \
      -D ENABLE_HYDRIDE:BOOL=${ALB_ENABLE_HYDRIDE} \
      -D ENABLE_SCOREC:BOOL=${ALB_ENABLE_SCOREC} \
      -D ENABLE_FELIX:BOOL=${ALB_ENABLE_FELIX} \
      -D ENABLE_MOR:BOOL=${ALB_ENABLE_MOR} \
      -D ENABLE_ALBANY_CI:BOOL=${ALB_ENABLE_AlbanyCI} \
      -D ENABLE_ASCR:BOOL=${ALB_ENABLE_ASCR} \
      -D ENABLE_SG_MP:BOOL=ON \
      -D LAME_INCLUDE_DIR:FILEPATH="$ALB_LAME_INC_DIR" \
      -D LAME_LIBRARY_DIR:FILEPATH="$ALB_LAME_LIB_DIR" \
       ../

#-D CMAKE_EXE_LINKER_FLAGS:STRING="-no-ip" \
