#!/bin/sh
#
export TRILINOS_HOME=/repository/usr/local/trilinos/votds/Trilinos
BUILD_DIR=`pwd`
INSTALL_DIR=/repository/usr/local/trilinos/votds/MPI_RELD_SO
BOOST_DIR=/repository/usr/local/boost/boost_1_51_0
MPI_BASE_DIR=/repository/usr/local/gcc/gcc-4.7.2
NETCDF=/repository/usr/local/parallel/netcdf-4.2.1.1
HDFDIR=/repository/usr/local/parallel/hdf5-1.8.9
MKL_PATH=/repository/usr/local/intel
BLAS_LA_LIBS="$MKL_PATH/mkl/lib/intel64/libmkl_intel_lp64.so;$MKL_PATH/mkl/lib/intel64/libmkl_intel_thread.so;$MKL_PATH/mkl/lib/intel64/libmkl_core.so;$MKL_PATH/lib/intel64/libiomp5.so;/usr/lib64/libpthread.so"
export BOOST_ROOT=$BOOST_DIR
EXTRA_ARGS=$@



##Get new Dakota

#wget -nv --no-check-certificate \
# http://development.sandia.gov/dakota/distributions/dakota/votd/Dakota_votd.src.tar.gz
#gunzip Dakota_votd.src.tar.gz

#(cd $TRILINOS_HOME/packages/TriKota; rm -rf Dakota; tar -xvf $BUILD_DIR/Dakota_votd.src.tar)

##end Dakota update

rm -f CMakeCache.txt

cmake \
	-D CMAKE_BUILD_TYPE:STRING=RELWITHDEBINFO \
	-D DART_TESTING_TIMEOUT:STRING=600 \
    -D BUILD_SHARED_LIBS:BOOL=ON \
	-D TPL_ENABLE_Boost:BOOL=ON \
	-D Trilinos_ENABLE_ThreadPool:BOOL=ON \
	-D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
	-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
	-D TPL_ENABLE_MPI:BOOL=ON \
	-D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
\
	-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
	-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
	-D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
	-D Trilinos_ENABLE_TESTS:BOOL=OFF \
	-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
\
	-D Trilinos_ENABLE_Teuchos:BOOL=ON \
	-D Trilinos_ENABLE_Shards:BOOL=ON \
	-D Trilinos_ENABLE_Sacado:BOOL=ON \
	-D Trilinos_ENABLE_Epetra:BOOL=ON \
	-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
	-D Trilinos_ENABLE_Ifpack:BOOL=ON \
	-D Trilinos_ENABLE_AztecOO:BOOL=ON \
	-D Trilinos_ENABLE_Amesos:BOOL=ON \
	-D Trilinos_ENABLE_Anasazi:BOOL=ON \
	-D Trilinos_ENABLE_Belos:BOOL=ON \
	-D Trilinos_ENABLE_ML:BOOL=ON \
	-D Trilinos_ENABLE_Phalanx:BOOL=ON \
	-D Trilinos_ENABLE_Intrepid:BOOL=ON \
	-D Trilinos_ENABLE_NOX:BOOL=ON \
	-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
	-D Trilinos_ENABLE_Thyra:BOOL=ON \
	-D Trilinos_ENABLE_Rythmos:BOOL=ON \
	-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
	-D Trilinos_ENABLE_OptiPack:BOOL=ON \
	-D Trilinos_ENABLE_GlobiPack:BOOL=ON \
	-D Trilinos_ENABLE_Stokhos:BOOL=ON \
	-D Trilinos_ENABLE_Isorropia:BOOL=ON \
	-D Trilinos_ENABLE_Piro:BOOL=ON \
	-D Trilinos_ENABLE_STK:BOOL=ON \
	-D Trilinos_ENABLE_Teko:BOOL=ON \
	-D Trilinos_ENABLE_Zoltan:BOOL=ON\
\
	-D Trilinos_ENABLE_Mesquite:BOOL=OFF\
	-D Trilinos_ENABLE_FEI:BOOL=OFF\
\
	-D Phalanx_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
	-D Stokhos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
	-D Stratimikos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
\
	-D Trilinos_ENABLE_TriKota:BOOL=ON \
	-D TriKota_ENABLE_DakotaCMake:BOOL=ON \
	-D ENABLE_DAKOTA_TESTS:BOOL=OFF \
	-D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
\
	-D Trilinos_ENABLE_SEACAS:BOOL=ON \
	-D Trilinos_ENABLE_Pamgen:BOOL=ON \
	-D TPL_ENABLE_Netcdf:BOOL=ON \
	-D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
	-D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
    -D TPL_ENABLE_HDF5:BOOL=ON \
    -D HDF5_INCLUDE_DIRS:PATH=$HDFDIR/include \
    -D HDF5_LIBRARY_DIRS:PATH=$HDFDIR/lib \
    -D TPL_ENABLE_BLAS:STRING=ON \
    -D TPL_ENABLE_LAPACK:STRING=ON \
    -D TPL_BLAS_LIBRARIES:STRING=$BLAS_LA_LIBS \
    -D BLAS_LIBS:STRING=$BLAS_LA_LIBS \
    -D TPL_LAPACK_LIBRARIES:STRING=$BLAS_LA_LIBS \
    -D LAPACK_LIBS:STRING="$BLAS_LA_LIBS;/usr/lib64/libdl.so" \
\
	-D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
$EXTRA_ARGS \
${TRILINOS_HOME}





#	-D CMAKE_CXX_FLAGS:STRING="-g -fno-var-tracking" \
#	-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
#    -D Trilinos_ENABLE_DEBUG:BOOL=ON \

#	-D CMAKE_BUILD_TYPE:STRING=NONE \
#	-D CMAKE_CXX_FLAGS:STRING="-g -O2 -fno-var-tracking" \
#	-D CMAKE_BUILD_TYPE:STRING=RELWITHDEBINFO \

#    -D Trilinos_EXTRA_LINK_FLAGS:STRING=${FORTRAN_LIBS} \
#    -D BLAS_LIBRARY_DIRS:FILEPATH=$BLASDIR \
#    -D BLAS_LIBRARY_NAMES:STRING="acml" \
#    -D LAPACK_LIBRARY_DIRS:FILEPATH=$BLASDIR \
#    -D LAPACK_LIBRARY_NAMES:STRING="acml" \
#    -D BLAS_LIBS:string="$BLASDIR/libacml.a" \
#    -D LAPACK_LIBS:string="$BLASDIR/libacml.a;$DAK_FORTRAN_LIBS" \
