#!/bin/sh
#
export TRILINOS_HOME=/repository/usr/local/trilinos/votds/Trilinos
BUILD_DIR=`pwd`
INSTALL_DIR=/repository/usr/local/trilinos/votds/MPI_RELD
BOOST_DIR=/repository/usr/local/boost/boost_1_53_0
MPI_BASE_DIR=/repository/usr/local/gcc/gcc-4.7.2
NETCDF=/repository/usr/local/parallel/netcdf-4.2.1.1
HDFDIR=/repository/usr/local/parallel/hdf5-1.8.9
PARMETISDIR=/repository/usr/local/parallel/ParMetis-3.1.1
MKL_PATH=/repository/usr/local/intel
LABLAS_LIBRARY_DIRS="$MKL_PATH/mkl/lib/intel64;/usr/lib64"
LABLAS_LIBRARY_NAMES="mkl_intel_lp64;mkl_sequential;mkl_core;pthread"
#BLASDIR=/sierra/Sntools/extras/compilers/acml4.3.0/gfortran64/lib
OPENNURBS_PATH=/repository/usr/local/opennurbs_20111122
#FORTRAN_LIBS="-lgfortran"
#DAK_FORTRAN_LIBS=/sierra/Sntools/extras/compilers/gcc-4.6.3/lib64/libgfortran.a
# Needed for Dakota (??)
export BOOST_ROOT=$BOOST_DIR
EXTRA_ARGS=$@



##Get new Dakota

# svn checkout https://software.sandia.gov/svn/public/dakota/public/trunk Dakota

#wget -nv --no-check-certificate \
# http://development.sandia.gov/dakota/distributions/dakota/votd/Dakota_votd.src.tar.gz
#gunzip Dakota_votd.src.tar.gz

#(cd $TRILINOS_HOME/packages/TriKota; rm -rf Dakota; tar -xvf $BUILD_DIR/Dakota_votd.src.tar)

# or via SVN
#
# svn co https://software.sandia.gov/svn/public/dakota/public/trunk Dakota

##end Dakota update

#rm -f CMakeCache.txt

cmake \
	-D CMAKE_BUILD_TYPE:STRING=RELWITHDEBINFO \
	-D DART_TESTING_TIMEOUT:STRING=600 \
	-D TPL_ENABLE_Boost:BOOL=ON \
	-D Trilinos_ENABLE_ThreadPool:BOOL=ON \
	-D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR/include \
	-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
	-D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF \
	-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
	-D TPL_ENABLE_MPI:BOOL=ON \
	-D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
	-D TPL_OpenNURBS_INCLUDE_DIRS:PATH=$OPENNURBS_PATH \
	-D TPL_OpenNURBS_LIBRARIES:PATH=$OPENNURBS_PATH/libopenNURBS.a \
	-D TPL_ENABLE_OpenNURBS:BOOL=ON \
\
	-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
	-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
	-D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
	-D Trilinos_ENABLE_TESTS:BOOL=OFF \
	-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
\
	-D Trilinos_ENABLE_Teuchos:BOOL=ON \
	-D Trilinos_ENABLE_Shards:BOOL=ON \
	-D Trilinos_ENABLE_Sacado:BOOL=ON \
	-D Trilinos_ENABLE_Epetra:BOOL=ON \
	-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
	-D Trilinos_ENABLE_Ifpack:BOOL=ON \
	-D Trilinos_ENABLE_AztecOO:BOOL=ON \
	-D Trilinos_ENABLE_Amesos:BOOL=ON \
	-D Trilinos_ENABLE_Anasazi:BOOL=ON \
	-D Trilinos_ENABLE_Belos:BOOL=ON \
	-D Trilinos_ENABLE_ML:BOOL=ON \
	-D Trilinos_ENABLE_Phalanx:BOOL=ON \
	-D Trilinos_ENABLE_Intrepid:BOOL=ON \
	-D Trilinos_ENABLE_NOX:BOOL=ON \
	-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
	-D Trilinos_ENABLE_Thyra:BOOL=ON \
	-D Trilinos_ENABLE_Rythmos:BOOL=ON \
	-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
	-D Trilinos_ENABLE_OptiPack:BOOL=ON \
	-D Trilinos_ENABLE_GlobiPack:BOOL=ON \
	-D Trilinos_ENABLE_Stokhos:BOOL=ON \
	-D Trilinos_ENABLE_Isorropia:BOOL=ON \
	-D Trilinos_ENABLE_Piro:BOOL=ON \
	-D Trilinos_ENABLE_STK:BOOL=ON \
	-D Trilinos_ENABLE_Teko:BOOL=ON \
	-D Trilinos_ENABLE_Zoltan:BOOL=ON\
\
	-D Trilinos_ENABLE_Mesquite:BOOL=OFF\
	-D Trilinos_ENABLE_FEI:BOOL=OFF\
\
	-D Phalanx_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
	-D Stokhos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
	-D Stratimikos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
\
	-D Trilinos_ENABLE_TriKota:BOOL=ON \
	-D TriKota_ENABLE_DakotaCMake:BOOL=ON \
	-D ENABLE_DAKOTA_TESTS:BOOL=OFF \
	-D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/lib \
\
	-D Trilinos_ENABLE_SEACAS:BOOL=ON \
	-D Trilinos_ENABLE_Pamgen:BOOL=ON \
\
	-D TPL_ENABLE_Netcdf:BOOL=ON \
	-D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
	-D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
\
    -D TPL_ENABLE_HDF5:BOOL=ON \
    -D HDF5_INCLUDE_DIRS:PATH=$HDFDIR/include \
    -D HDF5_LIBRARY_DIRS:PATH=$HDFDIR/lib \
\
    -D TPL_ENABLE_BLAS:STRING=ON \
    -D TPL_ENABLE_LAPACK:STRING=ON \
    -D BLAS_LIBRARY_DIRS:STRING=$LABLAS_LIBRARY_DIRS \
    -D BLAS_LIBRARY_NAMES:STRING=$LABLAS_LIBRARY_NAMES \
    -D LAPACK_LIBRARY_DIRS:STRING=$LABLAS_LIBRARY_DIRS \
    -D LAPACK_LIBRARY_NAMES:STRING=$LABLAS_LIBRARY_NAMES \
\
    -D TPL_ENABLE_ParMETIS:BOOL=ON \
    -D ParMETIS_INCLUDE_DIRS:PATH="${PARMETISDIR}" \
    -D ParMETIS_LIBRARY_DIRS:PATH="${PARMETISDIR}" \
\
	-D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
$EXTRA_ARGS \
${TRILINOS_HOME}





#	-D CMAKE_CXX_FLAGS:STRING="-g -fno-var-tracking" \
#	-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
#    -D Trilinos_ENABLE_DEBUG:BOOL=ON \

#	-D CMAKE_BUILD_TYPE:STRING=NONE \
#	-D CMAKE_CXX_FLAGS:STRING="-g -O2 -fno-var-tracking" \
#	-D CMAKE_BUILD_TYPE:STRING=RELWITHDEBINFO \

#    -D Trilinos_EXTRA_LINK_FLAGS:STRING=${FORTRAN_LIBS} \
#    -D BLAS_LIBRARY_DIRS:FILEPATH=$BLASDIR \
#    -D BLAS_LIBRARY_NAMES:STRING="acml" \
#    -D LAPACK_LIBRARY_DIRS:FILEPATH=$BLASDIR \
#    -D LAPACK_LIBRARY_NAMES:STRING="acml" \
#    -D BLAS_LIBS:string="$BLASDIR/libacml.a" \
#    -D LAPACK_LIBS:string="$BLASDIR/libacml.a;$DAK_FORTRAN_LIBS" \
