#!/bin/sh
#
export TRILINOS_HOME=/ascldap/users/gahanse/Codes/Trilinos
BUILD_DIR=`pwd`
INSTALL_DIR=/ascldap/users/gahanse/local/trilinos/LINUX_MPI
BOOST_DIR=/ascldap/users/gahanse/local/boost_1_47_0
MPI_BASE_DIR=/usr/netpub/mpi/OpenMPI/1.4/64Bit/gnu
NETCDF=/ascldap/users/gahanse/local
OPENNURBS_PATH=/ascldap/users/gahanse/local/src/opennurbs_20111122
# Needed for Dakota (??)
export BOOST_ROOT=$BOOST_DIR
EXTRA_ARGS=$@



##Get new Dakota

#wget -nv --no-check-certificate \
# http://development.sandia.gov/dakota/distributions/dakota/votd/Dakota_votd.src.tar.gz
#gunzip Dakota_votd.src.tar.gz

#(cd $TRILINOS_HOME/packages/TriKota; rm -rf Dakota; tar -xvf $BUILD_DIR/Dakota_votd.src.tar)

##end Dakota update

rm -f CMakeCache.txt

cmake \
	-D CMAKE_BUILD_TYPE:STRING=NONE \
	-D CMAKE_CXX_FLAGS:STRING="-g -O2 -fno-var-tracking" \
    -D Teuchos_ENABLE_DEFAULT_STACKTRACE:BOOL=ON \
	-D DART_TESTING_TIMEOUT:STRING=600 \
	-D TPL_ENABLE_Boost:BOOL=ON \
	-D Trilinos_ENABLE_ThreadPool:BOOL=ON \
	-D Boost_INCLUDE_DIRS:PATH=$BOOST_DIR \
	-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
	-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
	-D TPL_ENABLE_MPI:BOOL=ON \
	-D MPI_BASE_DIR:PATH=$MPI_BASE_DIR \
  -D TPL_OpenNURBS_INCLUDE_DIRS:PATH=$OPENNURBS_PATH \
  -D TPL_OpenNURBS_LIBRARIES:PATH=$OPENNURBS_PATH/libopenNURBS.a \
  -D TPL_ENABLE_OpenNURBS:BOOL=ON \
\
	-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
	-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
	-D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
	-D Trilinos_ENABLE_TESTS:BOOL=OFF \
	-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
\
	-D Trilinos_ENABLE_Teuchos:BOOL=ON \
	-D Trilinos_ENABLE_Shards:BOOL=ON \
	-D Trilinos_ENABLE_Sacado:BOOL=ON \
	-D Trilinos_ENABLE_Epetra:BOOL=ON \
	-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
	-D Trilinos_ENABLE_Ifpack:BOOL=ON \
	-D Trilinos_ENABLE_AztecOO:BOOL=ON \
	-D Trilinos_ENABLE_Amesos:BOOL=ON \
	-D Trilinos_ENABLE_Anasazi:BOOL=ON \
	-D Trilinos_ENABLE_Belos:BOOL=ON \
	-D Trilinos_ENABLE_ML:BOOL=ON \
	-D Trilinos_ENABLE_Phalanx:BOOL=ON \
	-D Trilinos_ENABLE_Intrepid:BOOL=ON \
	-D Trilinos_ENABLE_NOX:BOOL=ON \
	-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
	-D Trilinos_ENABLE_Thyra:BOOL=ON \
	-D Trilinos_ENABLE_Rythmos:BOOL=ON \
	-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
	-D Trilinos_ENABLE_OptiPack:BOOL=ON \
	-D Trilinos_ENABLE_GlobiPack:BOOL=ON \
	-D Trilinos_ENABLE_Stokhos:BOOL=ON \
	-D Trilinos_ENABLE_Isorropia:BOOL=ON \
	-D Trilinos_ENABLE_Piro:BOOL=ON \
	-D Trilinos_ENABLE_STK:BOOL=ON \
	-D Trilinos_ENABLE_Teko:BOOL=ON \
	-D Trilinos_ENABLE_Zoltan:BOOL=ON\
\
	-D Trilinos_ENABLE_Mesquite:BOOL=OFF\
	-D Trilinos_ENABLE_FEI:BOOL=OFF\
\
	-D Phalanx_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
	-D Stokhos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
	-D Stratimikos_ENABLE_TEUCHOS_TIME_MONITOR:BOOL=ON \
\
	-D Trilinos_ENABLE_TriKota:BOOL=ON \
	-D TriKota_ENABLE_DakotaCMake:BOOL=ON \
	-D ENABLE_DAKOTA_TESTS:BOOL=OFF \
	-D Boost_LIBRARY_DIRS:PATH=$BOOST_DIR/stage/lib \
\
	-D Trilinos_ENABLE_SEACAS:BOOL=ON \
	-D Trilinos_ENABLE_Pamgen:BOOL=ON \
	-D TPL_ENABLE_Netcdf:BOOL=ON \
	-D Netcdf_INCLUDE_DIRS:PATH=$NETCDF/include \
	-D Netcdf_LIBRARY_DIRS:PATH=$NETCDF/lib \
\
	-D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
$EXTRA_ARGS \
${TRILINOS_HOME}





#	-D CMAKE_CXX_FLAGS:STRING="-g -fno-var-tracking" \
#	-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
#    -D Trilinos_ENABLE_DEBUG:BOOL=ON \
