#!/bin/sh

export FMDB_INSTALL_DIR=/fasttmp/ghansen/SCOREC
export GMI_INSTALL_DIR=/fasttmp/ghansen/SCOREC
export MESHADAPT_INSTALL_DIR=/fasttmp/ghansen/SCOREC
export PARASOLID_INSTALL_DIR=/usr/local/parasolid/latest
export ALB_ENABLE_SCOREC=ON
export ALB_ENABLE_LCM=ON
export ALB_ENABLE_PARASOLID=ON
export TRILINOS_INSTALL_DIR=/fasttmp/ghansen/Trilinos/MPI_RELD

../doc/buildScripts/gahanse/do-cmake-albany-mpi
