#!/bin/sh

export FMDB_INSTALL_DIR=$SCOREC_SOFTWARE
export GMI_INSTALL_DIR=$SCOREC_SOFTWARE
export MESHADAPT_INSTALL_DIR=$SCOREC_SOFTWARE
export PARASOLID_INSTALL_DIR=/usr/local/parasolid/25.1.181
export ALB_ENABLE_SCOREC=ON
export ALB_ENABLE_LCM=ON
export ALB_ENABLE_PARASOLID=ON
export TRILINOS_INSTALL_DIR=/fasttmp/ghansen/Trilinos/MPI_DBG

../doc/buildScripts/gahanse/do-cmake-albany-mpi
