#!/bin/bash
# This is a sample Albany configuration script

# Cleanup old cmake files
rm -rf CMake*

#FIXME: the following needs needs to be changed to point to your Trilinos! 
TRILINOS_INSTALL_DIR=
ALBANY_SRC_DIR=
ALBANY_INSTALL_DIR=

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH=${TRILINOS_INSTALL_DIR} \
      -D CMAKE_INSTALL_PREFIX:PATH=${ALBANY_INSTALL_DIR} \
      -D CMAKE_CXX_FLAGS:STRING="" \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -D ENABLE_DEMO_PDES:BOOL=OFF \
      -D ENABLE_LANDICE:BOOL=ON \
      -D ENABLE_KOKKOS_UNDER_DEVELOPMENT:BOOL=ON \
      -D ENABLE_MPAS_INTERFACE:BOOL=ON \
      -D ENABLE_MESH_DEPENDS_ON_PARAMETERS:BOOL=OFF \
      -D BUILD_SHARED_LIBS:BOOL=OFF \
      -D Albany_BUILD_STATIC_EXE:BOOL=OFF \
      -D ENABLE_FAD_TYPE:STRING="SFad" \
      -D ALBANY_SFAD_SIZE=12 \
      -D ENABLE_MPAS_INTERFACE:BOOL=ON \
      ${ALBANY_SRC_DIR}

#      -D CMAKE_EXE_LINKER_FLAGS:STRING='-L/opt/gcc/8.3.0/snos/lib64 -lgcc_s -L/opt/gcc/8.3.0/snos/lib/gcc/x86_64-suse-linux/default -lgcc -static -Wl,-zmuldefs' \

