#!/bin/bash
#
# This is a sample Albany configuration script for ride and white.

# Cleanup old cmake files
rm -rf CMake*

# Set Trilinos build path
#FIXME: the following needs needs to be changed to point to your Trilinos! 
TRIBUILDDIR=${HOME}/Trilinos/build-kokkos-cuda/
TRILINSTALLDIR=$TRIBUILDDIR/install

cmake \
      -D ALBANY_TRILINOS_DIR:FILEPATH=$TRILINSTALLDIR \
      -D CMAKE_CXX_FLAGS:STRING="" \
      -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
      -D ENABLE_DEMO_PDES:BOOL=OFF \
      -D ENABLE_FELIX:BOOL=ON \
      -D ENABLE_QCAD:BOOL=OFF \
      -D ENABLE_LCM:BOOL=OFF \
      -D ENABLE_AERAS:BOOL=ON \
      -D ENABLE_SG:BOOL=OFF \
      -D ENABLE_ENSEMBLE:BOOL=OFF \
      -D ENABLE_STOKHOS:BOOL=OFF \
      -D ENABLE_ATO:BOOL=OFF \
      -D ENABLE_MOR:BOOL=OFF \
      -D ENABLE_PERFORMANCE_TESTS:BOOL=OFF \
      -D ALBANY_LIBRARIES_ONLY=OFF \
      -D ENABLE_INSTALL:BOOL=OFF \
      -D ENABLE_KOKKOS_UNDER_DEVELOPMENT:BOOL=ON \
..

#For debug build:
#  -D CMAKE_CXX_FLAGS:STRING="-g -G" \
#  -g is for host code, -G is for device code
#
