#!/bin/bash
# This is a sample MPAS configuration script, should be run from ${MALI_ROOT}/components/mpas-albany-landice/ directory

# FIXME: these need to be updated to point to the appropriate install directories
SCORPIO_INSTALL_DIR=
ALBANY_INSTALL_DIR=
TRILINOS_INSTALL_DIR=

# Get ALBANY_LINK_LIBS (Note: Need to add quotes to file)
source ${ALBANY_INSTALL_DIR}/export_albany.in

make clean \
  CORE=landice

make -j 16 gnu-cray \
  ALBANY=true \
  USE_PIO2=true \
  CORE=landice \
  PIO=${SCORPIO_INSTALL_DIR} \
  NETCDF=${NETCDF_DIR} \
  PNETCDF=${PARALLEL_NETCDF_DIR} \
  MPAS_EXTERNAL_LIBS="${ALBANY_LINK_LIBS} -Wl,-R${ALBANY_INSTALL_DIR}/lib -Wl,-R${TRILINOS_INSTALL_DIR}/lib -lstdc++ -L${CRAY_LIBSCI_PREFIX_DIR}/lib/libsci_gnu_mpi.a" \
  MPAS_EXTERNAL_INCLUDES="-I${ALBANY_INSTALL_DIR}/include -I${CRAY_LIBSCI_PREFIX_DIR}/include" \
  DEBUG=false \
  EXE_NAME=landice_model

