#!/usr/bin/env python

"""
A convenient way to manage and wrap Albany building and
testing, including Trilinos building.
"""

import argparse, sys, os, doctest, socket
from subprocess import Popen, PIPE

VERBOSE = False

"""
TODO:
 - How to allow user overrides?
 - allow multiple build types, IE: aeras + lcm
 - May need machine categorization in the case where lots of
   machines have the same env settings.
"""

ALBANY_BUILD_TYPES = \
{
    "basic" : [
    ],
    "trikota" : [
        ("TRILINOS_TRIKOTA",  "ON"),
    ],
    "lcm" : [
        ("ALBANY_LCM", "ON"),
        ("ALBANY_SG_MP", "ON"),
    ],
    "felix" : [
        ("ALBANY_LCM", "ON"),
        ("ALBANY_SG_MP", "ON"),
        ("ALBANY_MOR", "ON"),
        ("ALBANY_FELIX", "ON"),
        ("ALBANY_HYDRIDE", "ON"),
        ("ALBANY_AMP", "ON"),
        ("ALBANY_ATO", "ON"),
        ("ALBANY_QCAD", "ON"),
        ("ALBANY_ASCR", "ON"),
        ("ALBANY_AERAS", "ON"),
        ("ALBANY_64BIT_INT", "ON"),
        ("ALBANY_LAME", "ON"),
        ("ALBANY_DEMO_PDES", "ON"),
        ("ALBANY_MPAS_INTERFACE", "ON"),
        ("TRILINOS_PHALANX_TEUCHOS_TIME_MONITOR", "ON"),
        ("TRILINOS_STOKHOS_TEUCHOS_TIME_MONITOR", "ON"),
        ("TRILINOS_STRATIMIKOS_TEUCHOS_TIME_MONITOR", "ON"),
        ("TRILINOS_SUPERLU", "ON"),
        ("TRILINOS_PARMETIS", "ON"),
        ("TRILINOS_YAML", "ON"),
        ("TRILINOS_BLAS", "ON"),
        ("TRILINOS_DIDASKO", "ON"),
        ("TRILINOS_GALERI", "ON"),
        ("TRILINOS_GLOBIPACK", "ON"),
        ("TRILINOS_ISORROPIA", "ON"),
        ("TRILINOS_OPTIPACK", "ON"),
        ("TRILINOS_RBGEN", "ON"),
        ("TRILINOS_SCOREC", "ON"),
        ("TRILINOS_THREADPOOL", "ON"),
        ("TRILINOS_COUPLINGS", "ON"),
        ("TRILINOS_ZOLTAN2_EXPERIMENTAL", "ON"),
    ],
    "muelu_slu" : [
        ("TRILINOS_MUELU",   "ON"),
        ("TRILINOS_SUPERLU", "ON"),
    ],
    "muelu_klu" : [
        ("TRILINOS_MUELU", "ON"),
        ("TRILINOS_AMESOS_KLU2",  "ON"),
    ],
}

JENKINS_ENVS = \
[
    ("TRILDIR",        "$WORKSPACE/Trilinos"),
    ("TRILBUILDDIR",   "$TRILDIR/build"),
    ("TRILINSTALLDIR", "$TRILBUILDDIR/install"),
    ("ALBDIR",         "$WORKSPACE/Albany"),
    ("ALBBUILDDIR",    "$ALBDIR/build"),
    ("TRIKOTADIR",     "$TRILDIR/packages/TriKota"),

    # Warning: These not currently used
    ("TRILOUTDIR", "$WORKSPACE/Trilinos_out"),
    ("ALBOUTDIR",  "$WORKSPACE/Albany_out"),
    ("DAKOUTDIR",  "$WORKSPACE/Dakota_out"),
]

ALBANY_BUILD_MODES = \
{
    "release" : [
        ("ALBANY_BUILD_MODE",   "RELEASE"),
        ("TRILINOS_BUILD_MODE", "RELEASE")
    ],
    "debug"   : [
        ("ALBANY_BUILD_MODE",   "DEBUG"),
        ("TRILINOS_BUILD_MODE", "DEBUG"),
        ("BUILD_SHARED_LIBS",   "ON"),
        ("ALBANY_CXX_FLAGS",    "-ggdb"),
        ("TRILINOS_CXX_FLAGS",  "-ggdb")
    ]
}

COMPILERS = [
    "gcc",
    "intel",
    "clang",
    "pgi"
]

###############################################################################
def expect(condition, error_msg):
###############################################################################
    if (not condition):
        raise SystemExit(error_msg)

###############################################################################
def parse_command_line(args, description):
###############################################################################
    parser = argparse.ArgumentParser(
usage="""\n<WRAPPER> [-t <BUILD_TYPE>] [-m <BUILD_MODE>] [<OPTIONS>]

Examples assume <Albany>/tools/build_tools is in your PATH

\033[1mEXAMPLE:\033[0m
  > cd <Trilinos>/build
  > source <Albany>/tools/env/<my-env-file>
  > build-trilinos -t lcm -m debug
  > make -j 4 install
  > export TRILINSTALLDIR=`pwd`/install
  > cd <Albany>/build
  > build-albany -t lcm -m debug

\033[1mEXAMPLE USING NON-STANDARD BUILD LOCATIONS:\033[0m
  > cd <Trilinos-build-dir>
  > source <Albany>/tools/env/<my-env-file>
  > export TRILDIR=<path-to-trilinos-src>
  > build-trilinos -t lcm -m debug
  > make -j 4 install
  > export TRILINSTALLDIR=`pwd`/install
  > cd <Albany-build-dir>
  > export ALBDIR=<path-to-albany-src>
  > build-albany -t lcm -m debug

\033[1mEXAMPLE LETTING HARNESS MANAGE ENV:\033[0m
  > cd <Trilinos>/build
  > build-trilinos -t lcm -m debug -e -c gcc
  > make -j 4 install
  > export TRILINSTALLDIR=`pwd`/install
  > cd <Albany>/build
  > build-albany -t lcm -m debug -e -c gcc
""",

description=description,

formatter_class=argparse.RawTextHelpFormatter
)
    # Variables: Albany build type
    # Release or debug
    parser.add_argument("-t", action="store", choices=(ALBANY_BUILD_TYPES.keys()),
                        dest="build_type", default="basic", help="Choose build type")

    parser.add_argument("-m", action="store", choices=("debug", "release"),
                        dest="build_mode", default="release", help="Choose build mode")

    parser.add_argument("-v", action="store_true", dest="verbose", default=False,
                        help="Print shell commands as they are executed")

    parser.add_argument("-e", action="store_true", dest="manage_environment", default=False,
                        help="Have harness manage your environment for you")

    parser.add_argument("-c", action="store", dest="compiler", choices=COMPILERS, default=None,
                        help="Choose compiler. Only works with -e")

    parser.add_argument("mode", nargs="?", action="store", choices=("tril", "alb", "jenkins"),
                        default="jenkins", help="INTERNAL USE ONLY")

    args = parser.parse_args(args[1:])

    global VERBOSE
    VERBOSE = args.verbose

    expect(args.compiler == "none" or args.manage_environment,
           "Cannot use -c without also using -e")

    return args.mode, args.build_type, args.build_mode, args.manage_environment, args.compiler

###############################################################################
def run_cmd(command):
###############################################################################
    if (VERBOSE):
        print command

    proc = Popen(command, shell=True)
    proc.communicate()
    status = proc.wait()
    expect(status == 0, "Test failed")

###############################################################################
def set_env_for_build(build_key, env_map):
###############################################################################
    env_settings = env_map[build_key]

    for env_var, env_setting in env_settings:
        os.environ[env_var] = env_setting

###############################################################################
def set_jenkins_env():
###############################################################################
    for env_var, env_setting in JENKINS_ENVS:
        # Set env after dereferencing vars
        components = [os.environ[item[1:]] if item.startswith('$') else item for item in env_setting.split("/")]
        os.environ[env_var] = "/".join(components)

###############################################################################
def perform_test(mode, build_type, build_mode, manage_environment, compiler):
###############################################################################
    set_env_for_build(build_type, ALBANY_BUILD_TYPES)
    set_env_for_build(build_mode, ALBANY_BUILD_MODES)

    exe_dir = os.path.dirname(__file__)

    if (manage_environment):
        if (compiler is not None):
            os.environ["ATH_COMPILER"] = compiler

        nodename = socket.gethostname().split(".")[0]
        env_file_path = os.path.join(exe_dir, "env", "%s_env" % nodename)

        expect(os.path.exists(env_file_path), "env file '%s' does not exist" % env_file_path)

        env_cmd = "source %s &&" % env_file_path
    else:
        env_cmd = ""


    if (mode == "jenkins"):
        set_jenkins_env()

        test_script = os.path.join(exe_dir, "test_scripts", "test-engine")
        run_cmd("%s%s" % (env_cmd, test_script))

    elif (mode == "tril"):
        tril_fragment = os.path.join(exe_dir, "build_scripts", "cmake_fragments", "do-cmake-trilinos")
        run_cmd("%s%s" % (env_cmd, tril_fragment))

    elif (mode == "alb"):
        alb_fragment = os.path.join(exe_dir, "build_scripts", "cmake_fragments", "do-cmake-albany")
        run_cmd("%s%s" % (env_cmd, alb_fragment))

    else:
        expect(False, "Unrecognized mode '%s'" % mode)

###############################################################################
def _main_func(description):
###############################################################################
    if ("--test" in sys.argv):
        doctest.testmod()
        return

    mode, build_type, build_mode, manage_environment, compiler = \
        parse_command_line(sys.argv, description)

    perform_test(mode, build_type, build_mode, manage_environment, compiler)

###############################################################################

if (__name__ == "__main__"):
    _main_func(__doc__)
