#!/bin/bash

if [ -f ./CMakeCache.txt ]; then
    rm CMakeCache.txt
fi

# The Trilinos Dir is the same as the PREFIX entry from the
# Trilinos configuration script

cmake \
 -D ALBANY_TRILINOS_DIR:FILEPATH=$REMOTE/trilinos-install-gcc-release \
 -D CMAKE_CXX_FLAGS:STRING="-msse3 -DNDEBUG" \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
 -D ENABLE_LCM:BOOL=ON \
 -D ENABLE_ATO:BOOL=OFF \
 -D ENABLE_QCAD:BOOL=OFF \
 -D ENABLE_MOR:BOOL=OFF \
 -D ENABLE_SG:BOOL=OFF \
 -D ENABLE_ENSEMBLE:BOOL=OFF \
 -D ENABLE_FELIX:BOOL=OFF \
 -D ENABLE_LAME:BOOL=OFF \
 -D ENABLE_LAMENT:BOOL=OFF \
 -D ENABLE_CHECK_FPE:BOOL=OFF \
 -D ENABLE_FLUSH_DENORMALS:BOOL=OFF \
 -D ENABLE_KOKKOS_UNDER_DEVELOPMENT:BOOL=OFF \
 -D ALBANY_ENABLE_FORTRAN:BOOL=OFF \
 -D ENABLE_SLFAD:BOOL=OFF \
\
 -D ENABLE_ALBANY_EPETRA_EXE:BOOL=OFF \
 -D ENABLE_HYDRIDE:BOOL=OFF \
 -D ENABLE_AMP:BOOL=OFF \
 -D ENABLE_SCOREC:BOOL=OFF \
 -D ENABLE_SG_MP:BOOL=OFF \
 -D ENABLE_ASCR:BOOL=OFF \
 -D ENABLE_AERAS:BOOL=OFF \
 -D ENABLE_64BIT_INT:BOOL=OFF \
 -D ENABLE_INSTALL:BOOL=OFF \
 -D CMAKE_INSTALL_PREFIX:PATH=$REMOTE/albany-build-gcc-release \
 -D ENABLE_DEMO_PDES:BOOL=OFF \
 -D ENABLE_MPAS_INTERFACE:BOOL=OFF \
 -D ENABLE_CISM_INTERFACE:BOOL=OFF \
 -D ENABLE_USE_CISM_FLOW_PARAMETERS=OFF \
  \
 $REMOTE/src/Albany
